/*
 Navicat Premium Data Transfer

 Source Server         : MySQL
 Source Server Type    : MySQL
 Source Server Version : 50172
 Source Host           : localhost:3306
 Source Schema         : peqdb

 Target Server Type    : MySQL
 Target Server Version : 50172
 File Encoding         : 65001

 Date: 05/09/2020 14:31:50
*/

SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for aa_required_level_cost
-- ----------------------------
DROP TABLE IF EXISTS `aa_required_level_cost`;
CREATE TABLE `aa_required_level_cost`  (
  `skill_id` int(10) UNSIGNED NOT NULL,
  `level` int(10) UNSIGNED NOT NULL,
  `cost` int(10) UNSIGNED NOT NULL DEFAULT 0,
  `description` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'For reference only',
  PRIMARY KEY (`skill_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of aa_required_level_cost
-- ----------------------------
INSERT INTO `aa_required_level_cost` VALUES (292, 61, 1, 'Advanced Innate Strength');
INSERT INTO `aa_required_level_cost` VALUES (293, 61, 1, 'Advanced Innate Strength');
INSERT INTO `aa_required_level_cost` VALUES (294, 62, 1, 'Advanced Innate Strength');
INSERT INTO `aa_required_level_cost` VALUES (295, 62, 1, 'Advanced Innate Strength');
INSERT INTO `aa_required_level_cost` VALUES (296, 63, 1, 'Advanced Innate Strength');
INSERT INTO `aa_required_level_cost` VALUES (297, 63, 1, 'Advanced Innate Strength');
INSERT INTO `aa_required_level_cost` VALUES (298, 64, 1, 'Advanced Innate Strength');
INSERT INTO `aa_required_level_cost` VALUES (299, 64, 1, 'Advanced Innate Strength');
INSERT INTO `aa_required_level_cost` VALUES (300, 65, 1, 'Advanced Innate Strength');
INSERT INTO `aa_required_level_cost` VALUES (301, 65, 1, 'Advanced Innate Strength');
INSERT INTO `aa_required_level_cost` VALUES (302, 61, 1, 'Advanced Innate Stamina');
INSERT INTO `aa_required_level_cost` VALUES (303, 61, 1, 'Advanced Innate Stamina');
INSERT INTO `aa_required_level_cost` VALUES (304, 62, 1, 'Advanced Innate Stamina');
INSERT INTO `aa_required_level_cost` VALUES (305, 62, 1, 'Advanced Innate Stamina');
INSERT INTO `aa_required_level_cost` VALUES (306, 63, 1, 'Advanced Innate Stamina');
INSERT INTO `aa_required_level_cost` VALUES (307, 63, 1, 'Advanced Innate Stamina');
INSERT INTO `aa_required_level_cost` VALUES (308, 64, 1, 'Advanced Innate Stamina');
INSERT INTO `aa_required_level_cost` VALUES (309, 64, 1, 'Advanced Innate Stamina');
INSERT INTO `aa_required_level_cost` VALUES (310, 65, 1, 'Advanced Innate Stamina');
INSERT INTO `aa_required_level_cost` VALUES (311, 65, 1, 'Advanced Innate Stamina');
INSERT INTO `aa_required_level_cost` VALUES (312, 61, 1, 'Advanced Innate Agility');
INSERT INTO `aa_required_level_cost` VALUES (313, 61, 1, 'Advanced Innate Agility');
INSERT INTO `aa_required_level_cost` VALUES (314, 62, 1, 'Advanced Innate Agility');
INSERT INTO `aa_required_level_cost` VALUES (315, 62, 1, 'Advanced Innate Agility');
INSERT INTO `aa_required_level_cost` VALUES (316, 63, 1, 'Advanced Innate Agility');
INSERT INTO `aa_required_level_cost` VALUES (317, 63, 1, 'Advanced Innate Agility');
INSERT INTO `aa_required_level_cost` VALUES (318, 64, 1, 'Advanced Innate Agility');
INSERT INTO `aa_required_level_cost` VALUES (319, 64, 1, 'Advanced Innate Agility');
INSERT INTO `aa_required_level_cost` VALUES (320, 65, 1, 'Advanced Innate Agility');
INSERT INTO `aa_required_level_cost` VALUES (321, 65, 1, 'Advanced Innate Agility');
INSERT INTO `aa_required_level_cost` VALUES (322, 61, 1, 'Advanced Innate Dexterity');
INSERT INTO `aa_required_level_cost` VALUES (323, 61, 1, 'Advanced Innate Dexterity');
INSERT INTO `aa_required_level_cost` VALUES (324, 62, 1, 'Advanced Innate Dexterity');
INSERT INTO `aa_required_level_cost` VALUES (325, 62, 1, 'Advanced Innate Dexterity');
INSERT INTO `aa_required_level_cost` VALUES (326, 63, 1, 'Advanced Innate Dexterity');
INSERT INTO `aa_required_level_cost` VALUES (327, 63, 1, 'Advanced Innate Dexterity');
INSERT INTO `aa_required_level_cost` VALUES (328, 64, 1, 'Advanced Innate Dexterity');
INSERT INTO `aa_required_level_cost` VALUES (329, 64, 1, 'Advanced Innate Dexterity');
INSERT INTO `aa_required_level_cost` VALUES (330, 65, 1, 'Advanced Innate Dexterity');
INSERT INTO `aa_required_level_cost` VALUES (331, 65, 1, 'Advanced Innate Dexterity');
INSERT INTO `aa_required_level_cost` VALUES (332, 61, 1, 'Advanced Innate Intelligence');
INSERT INTO `aa_required_level_cost` VALUES (333, 61, 1, 'Advanced Innate Intelligence');
INSERT INTO `aa_required_level_cost` VALUES (334, 62, 1, 'Advanced Innate Intelligence');
INSERT INTO `aa_required_level_cost` VALUES (335, 62, 1, 'Advanced Innate Intelligence');
INSERT INTO `aa_required_level_cost` VALUES (336, 63, 1, 'Advanced Innate Intelligence');
INSERT INTO `aa_required_level_cost` VALUES (337, 63, 1, 'Advanced Innate Intelligence');
INSERT INTO `aa_required_level_cost` VALUES (338, 64, 1, 'Advanced Innate Intelligence');
INSERT INTO `aa_required_level_cost` VALUES (339, 64, 1, 'Advanced Innate Intelligence');
INSERT INTO `aa_required_level_cost` VALUES (340, 65, 1, 'Advanced Innate Intelligence');
INSERT INTO `aa_required_level_cost` VALUES (341, 65, 1, 'Advanced Innate Intelligence');
INSERT INTO `aa_required_level_cost` VALUES (342, 61, 1, 'Advanced Innate Wisdom');
INSERT INTO `aa_required_level_cost` VALUES (343, 61, 1, 'Advanced Innate Wisdom');
INSERT INTO `aa_required_level_cost` VALUES (344, 62, 1, 'Advanced Innate Wisdom');
INSERT INTO `aa_required_level_cost` VALUES (345, 62, 1, 'Advanced Innate Wisdom');
INSERT INTO `aa_required_level_cost` VALUES (346, 63, 1, 'Advanced Innate Wisdom');
INSERT INTO `aa_required_level_cost` VALUES (347, 63, 1, 'Advanced Innate Wisdom');
INSERT INTO `aa_required_level_cost` VALUES (348, 64, 1, 'Advanced Innate Wisdom');
INSERT INTO `aa_required_level_cost` VALUES (349, 64, 1, 'Advanced Innate Wisdom');
INSERT INTO `aa_required_level_cost` VALUES (350, 65, 1, 'Advanced Innate Wisdom');
INSERT INTO `aa_required_level_cost` VALUES (351, 65, 1, 'Advanced Innate Wisdom');
INSERT INTO `aa_required_level_cost` VALUES (352, 61, 1, 'Advanced Innate Charisma');
INSERT INTO `aa_required_level_cost` VALUES (353, 61, 1, 'Advanced Innate Charisma');
INSERT INTO `aa_required_level_cost` VALUES (354, 62, 1, 'Advanced Innate Charisma');
INSERT INTO `aa_required_level_cost` VALUES (355, 62, 1, 'Advanced Innate Charisma');
INSERT INTO `aa_required_level_cost` VALUES (356, 63, 1, 'Advanced Innate Charisma');
INSERT INTO `aa_required_level_cost` VALUES (357, 63, 1, 'Advanced Innate Charisma');
INSERT INTO `aa_required_level_cost` VALUES (358, 64, 1, 'Advanced Innate Charisma');
INSERT INTO `aa_required_level_cost` VALUES (359, 64, 1, 'Advanced Innate Charisma');
INSERT INTO `aa_required_level_cost` VALUES (360, 65, 1, 'Advanced Innate Charisma');
INSERT INTO `aa_required_level_cost` VALUES (361, 65, 1, 'Advanced Innate Charisma');
INSERT INTO `aa_required_level_cost` VALUES (362, 61, 1, 'Warding of Solusek');
INSERT INTO `aa_required_level_cost` VALUES (363, 61, 1, 'Warding of Solusek');
INSERT INTO `aa_required_level_cost` VALUES (364, 62, 1, 'Warding of Solusek');
INSERT INTO `aa_required_level_cost` VALUES (365, 62, 1, 'Warding of Solusek');
INSERT INTO `aa_required_level_cost` VALUES (366, 63, 1, 'Warding of Solusek');
INSERT INTO `aa_required_level_cost` VALUES (367, 63, 1, 'Warding of Solusek');
INSERT INTO `aa_required_level_cost` VALUES (368, 64, 1, 'Warding of Solusek');
INSERT INTO `aa_required_level_cost` VALUES (369, 64, 1, 'Warding of Solusek');
INSERT INTO `aa_required_level_cost` VALUES (370, 65, 1, 'Warding of Solusek');
INSERT INTO `aa_required_level_cost` VALUES (371, 65, 1, 'Warding of Solusek');
INSERT INTO `aa_required_level_cost` VALUES (372, 61, 1, 'Blessing of E\'ci');
INSERT INTO `aa_required_level_cost` VALUES (373, 61, 1, 'Blessing of E\'ci');
INSERT INTO `aa_required_level_cost` VALUES (374, 62, 1, 'Blessing of E\'ci');
INSERT INTO `aa_required_level_cost` VALUES (375, 62, 1, 'Blessing of E\'ci');
INSERT INTO `aa_required_level_cost` VALUES (376, 63, 1, 'Blessing of E\'ci');
INSERT INTO `aa_required_level_cost` VALUES (377, 63, 1, 'Blessing of E\'ci');
INSERT INTO `aa_required_level_cost` VALUES (378, 64, 1, 'Blessing of E\'ci');
INSERT INTO `aa_required_level_cost` VALUES (379, 64, 1, 'Blessing of E\'ci');
INSERT INTO `aa_required_level_cost` VALUES (380, 65, 1, 'Blessing of E\'ci');
INSERT INTO `aa_required_level_cost` VALUES (381, 65, 1, 'Blessing of E\'ci');
INSERT INTO `aa_required_level_cost` VALUES (382, 61, 1, 'Marr\'s Protection');
INSERT INTO `aa_required_level_cost` VALUES (383, 61, 1, 'Marr\'s Protection');
INSERT INTO `aa_required_level_cost` VALUES (384, 62, 1, 'Marr\'s Protection');
INSERT INTO `aa_required_level_cost` VALUES (385, 62, 1, 'Marr\'s Protection');
INSERT INTO `aa_required_level_cost` VALUES (386, 63, 1, 'Marr\'s Protection');
INSERT INTO `aa_required_level_cost` VALUES (387, 63, 1, 'Marr\'s Protection');
INSERT INTO `aa_required_level_cost` VALUES (388, 64, 1, 'Marr\'s Protection');
INSERT INTO `aa_required_level_cost` VALUES (389, 64, 1, 'Marr\'s Protection');
INSERT INTO `aa_required_level_cost` VALUES (390, 65, 1, 'Marr\'s Protection');
INSERT INTO `aa_required_level_cost` VALUES (391, 65, 1, 'Marr\'s Protection');
INSERT INTO `aa_required_level_cost` VALUES (392, 61, 1, 'Shroud of the Faceless');
INSERT INTO `aa_required_level_cost` VALUES (393, 61, 1, 'Shroud of the Faceless');
INSERT INTO `aa_required_level_cost` VALUES (394, 62, 1, 'Shroud of the Faceless');
INSERT INTO `aa_required_level_cost` VALUES (395, 62, 1, 'Shroud of the Faceless');
INSERT INTO `aa_required_level_cost` VALUES (396, 63, 1, 'Shroud of the Faceless');
INSERT INTO `aa_required_level_cost` VALUES (397, 63, 1, 'Shroud of the Faceless');
INSERT INTO `aa_required_level_cost` VALUES (398, 64, 1, 'Shroud of the Faceless');
INSERT INTO `aa_required_level_cost` VALUES (399, 64, 1, 'Shroud of the Faceless');
INSERT INTO `aa_required_level_cost` VALUES (400, 65, 1, 'Shroud of the Faceless');
INSERT INTO `aa_required_level_cost` VALUES (401, 65, 1, 'Shroud of the Faceless');
INSERT INTO `aa_required_level_cost` VALUES (402, 61, 1, 'Bertoxxulous\' Gift');
INSERT INTO `aa_required_level_cost` VALUES (403, 61, 1, 'Bertoxxulous\' Gift');
INSERT INTO `aa_required_level_cost` VALUES (404, 62, 1, 'Bertoxxulous\' Gift');
INSERT INTO `aa_required_level_cost` VALUES (405, 62, 1, 'Bertoxxulous\' Gift');
INSERT INTO `aa_required_level_cost` VALUES (406, 63, 1, 'Bertoxxulous\' Gift');
INSERT INTO `aa_required_level_cost` VALUES (407, 63, 1, 'Bertoxxulous\' Gift');
INSERT INTO `aa_required_level_cost` VALUES (408, 64, 1, 'Bertoxxulous\' Gift');
INSERT INTO `aa_required_level_cost` VALUES (409, 64, 1, 'Bertoxxulous\' Gift');
INSERT INTO `aa_required_level_cost` VALUES (410, 65, 1, 'Bertoxxulous\' Gift');
INSERT INTO `aa_required_level_cost` VALUES (411, 65, 1, 'Bertoxxulous\' Gift');
INSERT INTO `aa_required_level_cost` VALUES (418, 61, 2, 'Planar Power');
INSERT INTO `aa_required_level_cost` VALUES (419, 62, 2, 'Planar Power');
INSERT INTO `aa_required_level_cost` VALUES (420, 63, 2, 'Planar Power');
INSERT INTO `aa_required_level_cost` VALUES (421, 64, 2, 'Planar Power');
INSERT INTO `aa_required_level_cost` VALUES (422, 65, 2, 'Planar Power');
INSERT INTO `aa_required_level_cost` VALUES (423, 61, 3, 'Planar Durability');
INSERT INTO `aa_required_level_cost` VALUES (424, 63, 3, 'Planar Durability');
INSERT INTO `aa_required_level_cost` VALUES (425, 65, 3, 'Planar Durability');
INSERT INTO `aa_required_level_cost` VALUES (426, 61, 3, 'Innate Enlightenment');
INSERT INTO `aa_required_level_cost` VALUES (427, 62, 3, 'Innate Enlightenment');
INSERT INTO `aa_required_level_cost` VALUES (428, 63, 3, 'Innate Enlightenment');
INSERT INTO `aa_required_level_cost` VALUES (429, 64, 3, 'Innate Enlightenment');
INSERT INTO `aa_required_level_cost` VALUES (430, 65, 3, 'Innate Enlightenment');
INSERT INTO `aa_required_level_cost` VALUES (434, 62, 2, 'Advanced Healing Adept');
INSERT INTO `aa_required_level_cost` VALUES (435, 63, 4, 'Advanced Healing Adept');
INSERT INTO `aa_required_level_cost` VALUES (436, 64, 6, 'Advanced Healing Adept');
INSERT INTO `aa_required_level_cost` VALUES (437, 62, 2, 'Advanced Healing Gift');
INSERT INTO `aa_required_level_cost` VALUES (438, 63, 4, 'Advanced Healing Gift');
INSERT INTO `aa_required_level_cost` VALUES (439, 64, 6, 'Advanced Healing Gift');
INSERT INTO `aa_required_level_cost` VALUES (440, 62, 2, 'Coup de Grace');
INSERT INTO `aa_required_level_cost` VALUES (441, 63, 2, 'Coup de Grace');
INSERT INTO `aa_required_level_cost` VALUES (442, 64, 2, 'Coup de Grace');
INSERT INTO `aa_required_level_cost` VALUES (443, 62, 3, 'Fury of the Ages');
INSERT INTO `aa_required_level_cost` VALUES (444, 63, 3, 'Fury of the Ages');
INSERT INTO `aa_required_level_cost` VALUES (445, 64, 3, 'Fury of the Ages');
INSERT INTO `aa_required_level_cost` VALUES (446, 62, 3, 'Mastery of the Past');
INSERT INTO `aa_required_level_cost` VALUES (447, 63, 3, 'Mastery of the Past');
INSERT INTO `aa_required_level_cost` VALUES (448, 64, 3, 'Mastery of the Past');
INSERT INTO `aa_required_level_cost` VALUES (449, 61, 3, 'Lightning Reflexes');
INSERT INTO `aa_required_level_cost` VALUES (459, 61, 2, 'Radiant Cure');
INSERT INTO `aa_required_level_cost` VALUES (460, 63, 4, 'Radiant Cure');
INSERT INTO `aa_required_level_cost` VALUES (461, 65, 6, 'Radiant Cure');
INSERT INTO `aa_required_level_cost` VALUES (462, 63, 2, 'Hastened Divinity');
INSERT INTO `aa_required_level_cost` VALUES (463, 64, 2, 'Hastened Divinity');
INSERT INTO `aa_required_level_cost` VALUES (464, 65, 2, 'Hastened Divinity');
INSERT INTO `aa_required_level_cost` VALUES (468, 63, 2, 'Hastened Purification of the Soul');
INSERT INTO `aa_required_level_cost` VALUES (469, 64, 2, 'Hastened Purification of the Soul');
INSERT INTO `aa_required_level_cost` VALUES (470, 65, 2, 'Hastened Purification of the Soul');
INSERT INTO `aa_required_level_cost` VALUES (471, 63, 2, 'Hastened Gathering');
INSERT INTO `aa_required_level_cost` VALUES (472, 64, 2, 'Hastened Gathering');
INSERT INTO `aa_required_level_cost` VALUES (473, 65, 2, 'Hastened Gathering');
INSERT INTO `aa_required_level_cost` VALUES (474, 63, 2, 'Hastened Rabidity');
INSERT INTO `aa_required_level_cost` VALUES (475, 64, 2, 'Hastened Rabidity');
INSERT INTO `aa_required_level_cost` VALUES (476, 65, 2, 'Hastened Rabidity');
INSERT INTO `aa_required_level_cost` VALUES (477, 63, 2, 'Hastened Exodus');
INSERT INTO `aa_required_level_cost` VALUES (478, 64, 2, 'Hastened Exodus');
INSERT INTO `aa_required_level_cost` VALUES (479, 65, 2, 'Hastened Exodus');
INSERT INTO `aa_required_level_cost` VALUES (480, 63, 2, 'Hastened Root');
INSERT INTO `aa_required_level_cost` VALUES (481, 64, 2, 'Hastened Root');
INSERT INTO `aa_required_level_cost` VALUES (482, 65, 2, 'Hastened Root');
INSERT INTO `aa_required_level_cost` VALUES (483, 63, 2, 'Hastened Mending');
INSERT INTO `aa_required_level_cost` VALUES (484, 64, 2, 'Hastened Mending');
INSERT INTO `aa_required_level_cost` VALUES (485, 65, 2, 'Hastened Mending');
INSERT INTO `aa_required_level_cost` VALUES (486, 63, 2, 'Hastened Banishment');
INSERT INTO `aa_required_level_cost` VALUES (487, 64, 4, 'Hastened Banishment');
INSERT INTO `aa_required_level_cost` VALUES (488, 65, 6, 'Hastened Banishment');
INSERT INTO `aa_required_level_cost` VALUES (489, 63, 2, 'Hastened Instigation');
INSERT INTO `aa_required_level_cost` VALUES (490, 64, 2, 'Hastened Instigation');
INSERT INTO `aa_required_level_cost` VALUES (491, 65, 2, 'Hastened Instigation');
INSERT INTO `aa_required_level_cost` VALUES (492, 63, 2, 'Furious Rampage');
INSERT INTO `aa_required_level_cost` VALUES (493, 64, 2, 'Furious Rampage');
INSERT INTO `aa_required_level_cost` VALUES (494, 65, 2, 'Furious Rampage');
INSERT INTO `aa_required_level_cost` VALUES (495, 63, 2, 'Hastened Purification of the Body');
INSERT INTO `aa_required_level_cost` VALUES (496, 64, 2, 'Hastened Purification of the Body');
INSERT INTO `aa_required_level_cost` VALUES (497, 65, 2, 'Hastened Purification of the Body');
INSERT INTO `aa_required_level_cost` VALUES (498, 63, 2, 'Hasty Exit');
INSERT INTO `aa_required_level_cost` VALUES (499, 64, 2, 'Hasty Exit');
INSERT INTO `aa_required_level_cost` VALUES (500, 65, 2, 'Hasty Exit');
INSERT INTO `aa_required_level_cost` VALUES (501, 63, 2, 'Hastened Purification');
INSERT INTO `aa_required_level_cost` VALUES (502, 64, 2, 'Hastened Purification');
INSERT INTO `aa_required_level_cost` VALUES (503, 65, 2, 'Hastened Purification');
INSERT INTO `aa_required_level_cost` VALUES (504, 62, 3, 'Flash of Steel');
INSERT INTO `aa_required_level_cost` VALUES (505, 63, 3, 'Flash of Steel');
INSERT INTO `aa_required_level_cost` VALUES (506, 64, 3, 'Flash of Steel');
INSERT INTO `aa_required_level_cost` VALUES (507, 61, 3, 'Divine Arbitration');
INSERT INTO `aa_required_level_cost` VALUES (508, 63, 3, 'Divine Arbitration');
INSERT INTO `aa_required_level_cost` VALUES (509, 65, 3, 'Divine Arbitration');
INSERT INTO `aa_required_level_cost` VALUES (510, 61, 3, 'Wrath of the Wild');
INSERT INTO `aa_required_level_cost` VALUES (511, 63, 3, 'Wrath of the Wild');
INSERT INTO `aa_required_level_cost` VALUES (512, 65, 3, 'Wrath of the Wild');
INSERT INTO `aa_required_level_cost` VALUES (513, 61, 3, 'Virulent Paralysis');
INSERT INTO `aa_required_level_cost` VALUES (514, 63, 3, 'Virulent Paralysis');
INSERT INTO `aa_required_level_cost` VALUES (515, 65, 3, 'Virulent Paralysis');
INSERT INTO `aa_required_level_cost` VALUES (517, 61, 3, 'Eldritch Rune');
INSERT INTO `aa_required_level_cost` VALUES (518, 63, 3, 'Eldritch Rune');
INSERT INTO `aa_required_level_cost` VALUES (519, 65, 3, 'Eldritch Rune');
INSERT INTO `aa_required_level_cost` VALUES (520, 61, 3, 'Servant of Ro');
INSERT INTO `aa_required_level_cost` VALUES (521, 63, 3, 'Servant of Ro');
INSERT INTO `aa_required_level_cost` VALUES (522, 65, 3, 'Servant of Ro');
INSERT INTO `aa_required_level_cost` VALUES (523, 61, 3, 'Wake the Dead');
INSERT INTO `aa_required_level_cost` VALUES (524, 63, 2, 'Wake the Dead');
INSERT INTO `aa_required_level_cost` VALUES (525, 65, 1, 'Wake the Dead');
INSERT INTO `aa_required_level_cost` VALUES (526, 62, 5, 'Suspended Minion');
INSERT INTO `aa_required_level_cost` VALUES (527, 64, 3, 'Suspended Minion');
INSERT INTO `aa_required_level_cost` VALUES (528, 61, 4, 'Spirit Call');
INSERT INTO `aa_required_level_cost` VALUES (529, 63, 3, 'Spirit Call');
INSERT INTO `aa_required_level_cost` VALUES (530, 65, 2, 'Spirit Call');
INSERT INTO `aa_required_level_cost` VALUES (531, 63, 3, 'Celestial Renewal');
INSERT INTO `aa_required_level_cost` VALUES (532, 64, 6, 'Celestial Renewal');
INSERT INTO `aa_required_level_cost` VALUES (534, 61, 3, 'Hand of Piety');
INSERT INTO `aa_required_level_cost` VALUES (535, 63, 3, 'Hand of Piety');
INSERT INTO `aa_required_level_cost` VALUES (536, 65, 3, 'Hand of Piety');
INSERT INTO `aa_required_level_cost` VALUES (537, 63, 3, 'Mithaniel\'s Binding');
INSERT INTO `aa_required_level_cost` VALUES (538, 64, 3, 'Mithaniel\'s Binding');
INSERT INTO `aa_required_level_cost` VALUES (539, 63, 2, 'Mending of the Tranquil');
INSERT INTO `aa_required_level_cost` VALUES (540, 64, 4, 'Mending of the Tranquil');
INSERT INTO `aa_required_level_cost` VALUES (541, 65, 6, 'Mending of the Tranquil');
INSERT INTO `aa_required_level_cost` VALUES (542, 63, 2, 'Raging Flurry');
INSERT INTO `aa_required_level_cost` VALUES (543, 64, 4, 'Raging Flurry');
INSERT INTO `aa_required_level_cost` VALUES (544, 65, 6, 'Raging Flurry');
INSERT INTO `aa_required_level_cost` VALUES (545, 61, 3, 'Guardian of the Forest');
INSERT INTO `aa_required_level_cost` VALUES (546, 63, 3, 'Guardian of the Forest');
INSERT INTO `aa_required_level_cost` VALUES (547, 65, 3, 'Guradian of the Forest');
INSERT INTO `aa_required_level_cost` VALUES (548, 61, 4, 'Spirit of the Wood');
INSERT INTO `aa_required_level_cost` VALUES (549, 63, 3, 'Spirit of the Wood');
INSERT INTO `aa_required_level_cost` VALUES (550, 65, 2, 'Spirit of the Wood');
INSERT INTO `aa_required_level_cost` VALUES (551, 61, 2, 'Bestial Frenzy');
INSERT INTO `aa_required_level_cost` VALUES (552, 62, 2, 'Bestial Frenzy');
INSERT INTO `aa_required_level_cost` VALUES (553, 63, 2, 'Bestial Frenzy');
INSERT INTO `aa_required_level_cost` VALUES (554, 64, 2, 'Bestial Frenzy');
INSERT INTO `aa_required_level_cost` VALUES (555, 65, 2, 'Bestial Frenzy');
INSERT INTO `aa_required_level_cost` VALUES (556, 61, 2, 'Harmonious Attack');
INSERT INTO `aa_required_level_cost` VALUES (557, 62, 2, 'Harmonious Attack');
INSERT INTO `aa_required_level_cost` VALUES (558, 63, 2, 'Harmonious Attack');
INSERT INTO `aa_required_level_cost` VALUES (559, 64, 2, 'Harmonious Attack');
INSERT INTO `aa_required_level_cost` VALUES (560, 65, 2, 'Harmonious Attack');
INSERT INTO `aa_required_level_cost` VALUES (561, 61, 2, 'Knight\'s Advantage');
INSERT INTO `aa_required_level_cost` VALUES (562, 63, 4, 'Knight\'s Advantage');
INSERT INTO `aa_required_level_cost` VALUES (563, 65, 6, 'Knight\'s Advantage');
INSERT INTO `aa_required_level_cost` VALUES (564, 61, 3, 'Ferocity');
INSERT INTO `aa_required_level_cost` VALUES (565, 63, 3, 'Ferocity');
INSERT INTO `aa_required_level_cost` VALUES (566, 65, 3, 'Ferocity');
INSERT INTO `aa_required_level_cost` VALUES (568, 63, 2, 'Sionachie\'s Crescendo');
INSERT INTO `aa_required_level_cost` VALUES (569, 64, 2, 'Sionachie\'s Crescendo');
INSERT INTO `aa_required_level_cost` VALUES (570, 65, 2, 'Sionachie\'s Crescendo');
INSERT INTO `aa_required_level_cost` VALUES (571, 63, 2, 'Ayonae\'s Tutelage');
INSERT INTO `aa_required_level_cost` VALUES (572, 64, 2, 'Ayonae\'s Tutelage');
INSERT INTO `aa_required_level_cost` VALUES (573, 65, 2, 'Ayonae\'s Tutelage');
INSERT INTO `aa_required_level_cost` VALUES (574, 61, 3, 'Feigned Minion');
INSERT INTO `aa_required_level_cost` VALUES (575, 63, 3, 'Feigned Minion');
INSERT INTO `aa_required_level_cost` VALUES (576, 65, 3, 'Feigned Minion');
INSERT INTO `aa_required_level_cost` VALUES (577, 61, 2, 'Unfailing Divinity');
INSERT INTO `aa_required_level_cost` VALUES (578, 63, 4, 'Unfailing Divinity');
INSERT INTO `aa_required_level_cost` VALUES (579, 65, 6, 'Unfailing Divinity');
INSERT INTO `aa_required_level_cost` VALUES (580, 61, 4, 'Animation Empathy');
INSERT INTO `aa_required_level_cost` VALUES (581, 63, 3, 'Animation Empathy');
INSERT INTO `aa_required_level_cost` VALUES (582, 65, 2, 'Animation Empathy');
INSERT INTO `aa_required_level_cost` VALUES (583, 63, 2, 'Rush to Judgment');
INSERT INTO `aa_required_level_cost` VALUES (584, 64, 2, 'Rush to Judgment');
INSERT INTO `aa_required_level_cost` VALUES (585, 65, 2, 'Rush to Judgment');
INSERT INTO `aa_required_level_cost` VALUES (586, 61, 2, 'Living Shield');
INSERT INTO `aa_required_level_cost` VALUES (587, 63, 4, 'Living Shield');
INSERT INTO `aa_required_level_cost` VALUES (588, 65, 6, 'Living Shield');
INSERT INTO `aa_required_level_cost` VALUES (589, 61, 3, 'Consumption of the Soul');
INSERT INTO `aa_required_level_cost` VALUES (590, 63, 3, 'Consumption of the Soul');
INSERT INTO `aa_required_level_cost` VALUES (591, 65, 3, 'Consumption of the Soul');
INSERT INTO `aa_required_level_cost` VALUES (593, 61, 2, 'Fervent Blessing');
INSERT INTO `aa_required_level_cost` VALUES (594, 63, 4, 'Fervent Blessing');
INSERT INTO `aa_required_level_cost` VALUES (595, 65, 6, 'Fervent Blessing');
INSERT INTO `aa_required_level_cost` VALUES (596, 61, 2, 'Touch of the Wicked');
INSERT INTO `aa_required_level_cost` VALUES (597, 63, 2, 'Touch of the Wicked');
INSERT INTO `aa_required_level_cost` VALUES (598, 65, 2, 'Touch of the Wicked');
INSERT INTO `aa_required_level_cost` VALUES (599, 61, 2, 'Punishing Blade');
INSERT INTO `aa_required_level_cost` VALUES (600, 63, 4, 'Punishing Blade');
INSERT INTO `aa_required_level_cost` VALUES (601, 65, 6, 'Punishing Blade');
INSERT INTO `aa_required_level_cost` VALUES (602, 61, 3, 'Speed of the Knight');
INSERT INTO `aa_required_level_cost` VALUES (603, 63, 3, 'Speed of the Knight');
INSERT INTO `aa_required_level_cost` VALUES (604, 65, 3, 'Speed of the Knight');
INSERT INTO `aa_required_level_cost` VALUES (606, 61, 1, 'Nimble Evasion');
INSERT INTO `aa_required_level_cost` VALUES (607, 62, 1, 'Nimble Evasion');
INSERT INTO `aa_required_level_cost` VALUES (608, 63, 1, 'Nimble Evasion');
INSERT INTO `aa_required_level_cost` VALUES (609, 64, 1, 'Nimble Evasion');
INSERT INTO `aa_required_level_cost` VALUES (610, 65, 1, 'Nimble Evasion');
INSERT INTO `aa_required_level_cost` VALUES (616, 63, 5, 'Host of the Elements');
INSERT INTO `aa_required_level_cost` VALUES (617, 64, 4, 'Host of the Elements');
INSERT INTO `aa_required_level_cost` VALUES (618, 65, 3, 'Host of the Elements');
INSERT INTO `aa_required_level_cost` VALUES (619, 61, 3, 'Call of Xuzl');
INSERT INTO `aa_required_level_cost` VALUES (620, 63, 2, 'Call of Xuzl');
INSERT INTO `aa_required_level_cost` VALUES (621, 65, 1, 'Call of Xuzl');
INSERT INTO `aa_required_level_cost` VALUES (622, 61, 3, 'Hastened Stealth');
INSERT INTO `aa_required_level_cost` VALUES (623, 62, 3, 'Hastened Stealth');
INSERT INTO `aa_required_level_cost` VALUES (624, 63, 3, 'Hastened Stealth');
INSERT INTO `aa_required_level_cost` VALUES (625, 61, 1, 'Ingenuity');
INSERT INTO `aa_required_level_cost` VALUES (626, 63, 2, 'Ingenuity');
INSERT INTO `aa_required_level_cost` VALUES (627, 65, 3, 'Ingenuity');
INSERT INTO `aa_required_level_cost` VALUES (628, 62, 2, 'Fleet of Foot');
INSERT INTO `aa_required_level_cost` VALUES (629, 64, 4, 'Fleet of Foot');
INSERT INTO `aa_required_level_cost` VALUES (631, 61, 2, 'Tactical Mastery');
INSERT INTO `aa_required_level_cost` VALUES (632, 63, 3, 'Tactical Mastery');
INSERT INTO `aa_required_level_cost` VALUES (633, 65, 4, 'Tactical Mastery');
INSERT INTO `aa_required_level_cost` VALUES (646, 61, 2, 'Unholy Touch');
INSERT INTO `aa_required_level_cost` VALUES (647, 63, 4, 'Unholy Touch');
INSERT INTO `aa_required_level_cost` VALUES (648, 65, 6, 'Unholy Touch');
INSERT INTO `aa_required_level_cost` VALUES (652, 61, 2, 'Stalwart Endurance');
INSERT INTO `aa_required_level_cost` VALUES (1021, 51, 5, 'Mystical Attuning');
INSERT INTO `aa_required_level_cost` VALUES (1022, 55, 5, 'Mystical Attuning');
INSERT INTO `aa_required_level_cost` VALUES (1023, 60, 5, 'Mystical Attuning');
INSERT INTO `aa_required_level_cost` VALUES (1024, 65, 5, 'Mystical Attuning');
INSERT INTO `aa_required_level_cost` VALUES (1025, 65, 5, 'Mystical Attuning');
INSERT INTO `aa_required_level_cost` VALUES (7539, 80, 5, 'Mystical Attuning III');
INSERT INTO `aa_required_level_cost` VALUES (7540, 85, 5, 'Mystical Attuning III');
INSERT INTO `aa_required_level_cost` VALUES (7541, 85, 5, 'Mystical Attuning III');
INSERT INTO `aa_required_level_cost` VALUES (7542, 85, 5, 'Mystical Attuning III');
INSERT INTO `aa_required_level_cost` VALUES (7543, 85, 5, 'Mystical Attuning III');
INSERT INTO `aa_required_level_cost` VALUES (7800, 1, 0, 'Harm Touch');
INSERT INTO `aa_required_level_cost` VALUES (7801, 6, 0, 'Harm Touch');
INSERT INTO `aa_required_level_cost` VALUES (7802, 11, 0, 'Harm Touch');
INSERT INTO `aa_required_level_cost` VALUES (7803, 16, 0, 'Harm Touch');
INSERT INTO `aa_required_level_cost` VALUES (7804, 21, 0, 'Harm Touch');
INSERT INTO `aa_required_level_cost` VALUES (7805, 26, 0, 'Harm Touch');
INSERT INTO `aa_required_level_cost` VALUES (7806, 31, 0, 'Harm Touch');
INSERT INTO `aa_required_level_cost` VALUES (7807, 36, 0, 'Harm Touch');
INSERT INTO `aa_required_level_cost` VALUES (7808, 41, 0, 'Harm Touch');
INSERT INTO `aa_required_level_cost` VALUES (7809, 46, 0, 'Harm Touch');
INSERT INTO `aa_required_level_cost` VALUES (7810, 51, 3, 'Harm Touch');
INSERT INTO `aa_required_level_cost` VALUES (7811, 56, 4, 'Harm Touch');
INSERT INTO `aa_required_level_cost` VALUES (7812, 61, 5, 'Harm Touch');
INSERT INTO `aa_required_level_cost` VALUES (7813, 66, 6, 'Harm Touch');
INSERT INTO `aa_required_level_cost` VALUES (7814, 71, 7, 'Harm Touch');
INSERT INTO `aa_required_level_cost` VALUES (7815, 76, 8, 'Harm Touch');
INSERT INTO `aa_required_level_cost` VALUES (7816, 81, 8, 'Harm Touch');
INSERT INTO `aa_required_level_cost` VALUES (7817, 83, 9, 'Harm Touch');
INSERT INTO `aa_required_level_cost` VALUES (7850, 5, 0, 'Lay on Hands');
INSERT INTO `aa_required_level_cost` VALUES (7851, 11, 0, 'Lay on Hands');
INSERT INTO `aa_required_level_cost` VALUES (7852, 16, 0, 'Lay on Hands');
INSERT INTO `aa_required_level_cost` VALUES (7853, 21, 0, 'Lay on Hands');
INSERT INTO `aa_required_level_cost` VALUES (7854, 26, 0, 'Lay on Hands');
INSERT INTO `aa_required_level_cost` VALUES (7855, 31, 0, 'Lay on Hands');
INSERT INTO `aa_required_level_cost` VALUES (7856, 36, 0, 'Lay on Hands');
INSERT INTO `aa_required_level_cost` VALUES (7857, 41, 0, 'Lay on Hands');
INSERT INTO `aa_required_level_cost` VALUES (7858, 46, 0, 'Lay on Hands');
INSERT INTO `aa_required_level_cost` VALUES (7859, 51, 0, 'Lay on Hands');
INSERT INTO `aa_required_level_cost` VALUES (7860, 56, 3, 'Lay on Hands');
INSERT INTO `aa_required_level_cost` VALUES (7861, 61, 4, 'Lay on Hands');
INSERT INTO `aa_required_level_cost` VALUES (7862, 66, 5, 'Lay on Hands');
INSERT INTO `aa_required_level_cost` VALUES (7863, 71, 6, 'Lay on Hands');
INSERT INTO `aa_required_level_cost` VALUES (7864, 76, 7, 'Lay on Hands');
INSERT INTO `aa_required_level_cost` VALUES (7865, 81, 8, 'Lay on Hands');
INSERT INTO `aa_required_level_cost` VALUES (7866, 85, 9, 'Lay on Hands');

SET FOREIGN_KEY_CHECKS = 1;
