/*
 Navicat Premium Data Transfer

 Source Server         : MySQL
 Source Server Type    : MySQL
 Source Server Version : 50172
 Source Host           : localhost:3306
 Source Schema         : peqdb

 Target Server Type    : MySQL
 Target Server Version : 50172
 File Encoding         : 65001

 Date: 05/09/2020 15:03:08
*/

SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for name_filter
-- ----------------------------
DROP TABLE IF EXISTS `name_filter`;
CREATE TABLE `name_filter`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `name_search_index`(`name`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 278 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of name_filter
-- ----------------------------
INSERT INTO `name_filter` VALUES (1, '-GM');
INSERT INTO `name_filter` VALUES (218, 'aborshion');
INSERT INTO `name_filter` VALUES (2, 'abortion');
INSERT INTO `name_filter` VALUES (3, 'acid');
INSERT INTO `name_filter` VALUES (245, 'akka');
INSERT INTO `name_filter` VALUES (4, 'allah');
INSERT INTO `name_filter` VALUES (5, 'anal');
INSERT INTO `name_filter` VALUES (6, 'ass');
INSERT INTO `name_filter` VALUES (7, 'asshole');
INSERT INTO `name_filter` VALUES (8, 'ballbeater');
INSERT INTO `name_filter` VALUES (9, 'ballhitter');
INSERT INTO `name_filter` VALUES (10, 'balllicker');
INSERT INTO `name_filter` VALUES (11, 'ballsucker');
INSERT INTO `name_filter` VALUES (12, 'bangher');
INSERT INTO `name_filter` VALUES (13, 'bastard');
INSERT INTO `name_filter` VALUES (14, 'bastid');
INSERT INTO `name_filter` VALUES (208, 'bewb');
INSERT INTO `name_filter` VALUES (212, 'bewbs');
INSERT INTO `name_filter` VALUES (15, 'biatch');
INSERT INTO `name_filter` VALUES (222, 'Biotch');
INSERT INTO `name_filter` VALUES (16, 'bitch');
INSERT INTO `name_filter` VALUES (17, 'blow');
INSERT INTO `name_filter` VALUES (18, 'bodhisattva');
INSERT INTO `name_filter` VALUES (223, 'boner');
INSERT INTO `name_filter` VALUES (19, 'boob');
INSERT INTO `name_filter` VALUES (20, 'boobie');
INSERT INTO `name_filter` VALUES (210, 'bowjob');
INSERT INTO `name_filter` VALUES (21, 'breast');
INSERT INTO `name_filter` VALUES (22, 'browneye');
INSERT INTO `name_filter` VALUES (23, 'buddha');
INSERT INTO `name_filter` VALUES (24, 'butt');
INSERT INTO `name_filter` VALUES (25, 'capitalist');
INSERT INTO `name_filter` VALUES (26, 'cavedude');
INSERT INTO `name_filter` VALUES (27, 'cazic');
INSERT INTO `name_filter` VALUES (28, 'cheat');
INSERT INTO `name_filter` VALUES (29, 'chink');
INSERT INTO `name_filter` VALUES (262, 'chlamidia');
INSERT INTO `name_filter` VALUES (259, 'chlamydia');
INSERT INTO `name_filter` VALUES (30, 'christ');
INSERT INTO `name_filter` VALUES (260, 'clamydia');
INSERT INTO `name_filter` VALUES (31, 'clit');
INSERT INTO `name_filter` VALUES (32, 'cock');
INSERT INTO `name_filter` VALUES (33, 'coke');
INSERT INTO `name_filter` VALUES (34, 'communist');
INSERT INTO `name_filter` VALUES (35, 'coonass');
INSERT INTO `name_filter` VALUES (36, 'corrupt');
INSERT INTO `name_filter` VALUES (37, 'crack');
INSERT INTO `name_filter` VALUES (38, 'cracka');
INSERT INTO `name_filter` VALUES (39, 'cracker');
INSERT INTO `name_filter` VALUES (40, 'crank');
INSERT INTO `name_filter` VALUES (41, 'crap');
INSERT INTO `name_filter` VALUES (42, 'cSR');
INSERT INTO `name_filter` VALUES (43, 'cum');
INSERT INTO `name_filter` VALUES (44, 'cunt');
INSERT INTO `name_filter` VALUES (209, 'dammit');
INSERT INTO `name_filter` VALUES (45, 'damn');
INSERT INTO `name_filter` VALUES (46, 'deiffin');
INSERT INTO `name_filter` VALUES (47, 'democrat');
INSERT INTO `name_filter` VALUES (48, 'dick');
INSERT INTO `name_filter` VALUES (49, 'dingleberry');
INSERT INTO `name_filter` VALUES (50, 'diq');
INSERT INTO `name_filter` VALUES (51, 'dong');
INSERT INTO `name_filter` VALUES (52, 'donkeypunch');
INSERT INTO `name_filter` VALUES (53, 'douche');
INSERT INTO `name_filter` VALUES (54, 'drug');
INSERT INTO `name_filter` VALUES (230, 'dumbich');
INSERT INTO `name_filter` VALUES (224, 'dyke');
INSERT INTO `name_filter` VALUES (231, 'epeen');
INSERT INTO `name_filter` VALUES (55, 'EyeP');
INSERT INTO `name_filter` VALUES (56, 'eyepfreely');
INSERT INTO `name_filter` VALUES (57, 'fack');
INSERT INTO `name_filter` VALUES (58, 'fag');
INSERT INTO `name_filter` VALUES (213, 'Fagina');
INSERT INTO `name_filter` VALUES (219, 'Fart');
INSERT INTO `name_filter` VALUES (274, 'fart');
INSERT INTO `name_filter` VALUES (220, 'Farted');
INSERT INTO `name_filter` VALUES (59, 'fathernitwit');
INSERT INTO `name_filter` VALUES (60, 'feck');
INSERT INTO `name_filter` VALUES (61, 'fennin');
INSERT INTO `name_filter` VALUES (62, 'fuck');
INSERT INTO `name_filter` VALUES (225, 'fudgepacker');
INSERT INTO `name_filter` VALUES (63, 'fuk');
INSERT INTO `name_filter` VALUES (247, 'funbag');
INSERT INTO `name_filter` VALUES (64, 'fuqu');
INSERT INTO `name_filter` VALUES (214, 'Furtaco');
INSERT INTO `name_filter` VALUES (65, 'fuxxor');
INSERT INTO `name_filter` VALUES (229, 'gangbang');
INSERT INTO `name_filter` VALUES (255, 'genital');
INSERT INTO `name_filter` VALUES (66, 'ghey');
INSERT INTO `name_filter` VALUES (67, 'gM-');
INSERT INTO `name_filter` VALUES (68, 'gM_');
INSERT INTO `name_filter` VALUES (69, 'god');
INSERT INTO `name_filter` VALUES (265, 'gonorea');
INSERT INTO `name_filter` VALUES (264, 'gonorhea');
INSERT INTO `name_filter` VALUES (258, 'gonorrea');
INSERT INTO `name_filter` VALUES (257, 'gonorrhea');
INSERT INTO `name_filter` VALUES (70, 'goo');
INSERT INTO `name_filter` VALUES (71, 'gook');
INSERT INTO `name_filter` VALUES (236, 'Gopr');
INSERT INTO `name_filter` VALUES (72, 'grandCreation');
INSERT INTO `name_filter` VALUES (73, 'hebrew');
INSERT INTO `name_filter` VALUES (272, 'hepatitis');
INSERT INTO `name_filter` VALUES (74, 'heroin');
INSERT INTO `name_filter` VALUES (256, 'herpe');
INSERT INTO `name_filter` VALUES (75, 'hillBilly');
INSERT INTO `name_filter` VALUES (76, 'hitler');
INSERT INTO `name_filter` VALUES (77, 'hoe');
INSERT INTO `name_filter` VALUES (78, 'homo');
INSERT INTO `name_filter` VALUES (79, 'honkey');
INSERT INTO `name_filter` VALUES (80, 'hooker');
INSERT INTO `name_filter` VALUES (249, 'hooter');
INSERT INTO `name_filter` VALUES (237, 'Huffin');
INSERT INTO `name_filter` VALUES (81, 'innoruuk');
INSERT INTO `name_filter` VALUES (82, 'Isuccacocc');
INSERT INTO `name_filter` VALUES (83, 'itchy');
INSERT INTO `name_filter` VALUES (84, 'jackoff');
INSERT INTO `name_filter` VALUES (85, 'jehova');
INSERT INTO `name_filter` VALUES (86, 'jehovah');
INSERT INTO `name_filter` VALUES (87, 'jesus');
INSERT INTO `name_filter` VALUES (88, 'jew');
INSERT INTO `name_filter` VALUES (89, 'jigaboo');
INSERT INTO `name_filter` VALUES (244, 'jihad');
INSERT INTO `name_filter` VALUES (90, 'jiz');
INSERT INTO `name_filter` VALUES (91, 'karana');
INSERT INTO `name_filter` VALUES (92, 'kerafyrm');
INSERT INTO `name_filter` VALUES (93, 'kike');
INSERT INTO `name_filter` VALUES (239, 'Kilz');
INSERT INTO `name_filter` VALUES (263, 'klamidia');
INSERT INTO `name_filter` VALUES (261, 'klamydia');
INSERT INTO `name_filter` VALUES (94, 'kls');
INSERT INTO `name_filter` VALUES (95, 'klukluxklan');
INSERT INTO `name_filter` VALUES (96, 'kneeGrow');
INSERT INTO `name_filter` VALUES (248, 'knockers');
INSERT INTO `name_filter` VALUES (97, 'kunt');
INSERT INTO `name_filter` VALUES (98, 'labia');
INSERT INTO `name_filter` VALUES (99, 'lawli');
INSERT INTO `name_filter` VALUES (100, 'lawlicake');
INSERT INTO `name_filter` VALUES (101, 'lesbian');
INSERT INTO `name_filter` VALUES (243, 'lesbo');
INSERT INTO `name_filter` VALUES (102, 'lester');
INSERT INTO `name_filter` VALUES (103, 'level');
INSERT INTO `name_filter` VALUES (104, 'loot');
INSERT INTO `name_filter` VALUES (105, 'lootmeh');
INSERT INTO `name_filter` VALUES (106, 'lsd');
INSERT INTO `name_filter` VALUES (238, 'Mackal');
INSERT INTO `name_filter` VALUES (107, 'marijuana');
INSERT INTO `name_filter` VALUES (108, 'maryjane');
INSERT INTO `name_filter` VALUES (109, 'masterbait');
INSERT INTO `name_filter` VALUES (110, 'masterbate');
INSERT INTO `name_filter` VALUES (111, 'masturbait');
INSERT INTO `name_filter` VALUES (227, 'meatflap');
INSERT INTO `name_filter` VALUES (112, 'medirty');
INSERT INTO `name_filter` VALUES (113, 'messiah');
INSERT INTO `name_filter` VALUES (228, 'milf');
INSERT INTO `name_filter` VALUES (114, 'moelester');
INSERT INTO `name_filter` VALUES (115, 'mohlester');
INSERT INTO `name_filter` VALUES (116, 'nazi');
INSERT INTO `name_filter` VALUES (117, 'negro');
INSERT INTO `name_filter` VALUES (118, 'niga');
INSERT INTO `name_filter` VALUES (119, 'nigg');
INSERT INTO `name_filter` VALUES (120, 'nigga');
INSERT INTO `name_filter` VALUES (121, 'nigger');
INSERT INTO `name_filter` VALUES (122, 'nipple');
INSERT INTO `name_filter` VALUES (123, 'nork');
INSERT INTO `name_filter` VALUES (124, 'nympho');
INSERT INTO `name_filter` VALUES (125, 'panis');
INSERT INTO `name_filter` VALUES (271, 'papilloma');
INSERT INTO `name_filter` VALUES (126, 'penis');
INSERT INTO `name_filter` VALUES (127, 'pEQ');
INSERT INTO `name_filter` VALUES (275, 'phart');
INSERT INTO `name_filter` VALUES (128, 'pinkeye');
INSERT INTO `name_filter` VALUES (129, 'piss');
INSERT INTO `name_filter` VALUES (130, 'player');
INSERT INTO `name_filter` VALUES (131, 'poon');
INSERT INTO `name_filter` VALUES (277, 'poop');
INSERT INTO `name_filter` VALUES (221, 'Poot');
INSERT INTO `name_filter` VALUES (132, 'porchmonkey');
INSERT INTO `name_filter` VALUES (133, 'porn');
INSERT INTO `name_filter` VALUES (134, 'pot');
INSERT INTO `name_filter` VALUES (135, 'prick');
INSERT INTO `name_filter` VALUES (136, 'private');
INSERT INTO `name_filter` VALUES (137, 'pubic');
INSERT INTO `name_filter` VALUES (138, 'pussy');
INSERT INTO `name_filter` VALUES (139, 'pve');
INSERT INTO `name_filter` VALUES (140, 'pvp');
INSERT INTO `name_filter` VALUES (141, 'pwn');
INSERT INTO `name_filter` VALUES (142, 'quarm');
INSERT INTO `name_filter` VALUES (215, 'queef');
INSERT INTO `name_filter` VALUES (216, 'queeftaco');
INSERT INTO `name_filter` VALUES (143, 'Quirfag');
INSERT INTO `name_filter` VALUES (144, 'qunt');
INSERT INTO `name_filter` VALUES (145, 'raghead');
INSERT INTO `name_filter` VALUES (146, 'rallos');
INSERT INTO `name_filter` VALUES (147, 'rape');
INSERT INTO `name_filter` VALUES (148, 'redneck');
INSERT INTO `name_filter` VALUES (149, 'reno');
INSERT INTO `name_filter` VALUES (150, 'republican');
INSERT INTO `name_filter` VALUES (151, 'retard');
INSERT INTO `name_filter` VALUES (152, 'satan');
INSERT INTO `name_filter` VALUES (276, 'schit');
INSERT INTO `name_filter` VALUES (211, 'Schlong');
INSERT INTO `name_filter` VALUES (153, 'screw');
INSERT INTO `name_filter` VALUES (226, 'scrotum');
INSERT INTO `name_filter` VALUES (154, 'seaman');
INSERT INTO `name_filter` VALUES (155, 'seamans');
INSERT INTO `name_filter` VALUES (240, 'secks');
INSERT INTO `name_filter` VALUES (242, 'secsea');
INSERT INTO `name_filter` VALUES (241, 'secsee');
INSERT INTO `name_filter` VALUES (156, 'seeman');
INSERT INTO `name_filter` VALUES (157, 'seemen');
INSERT INTO `name_filter` VALUES (158, 'semen');
INSERT INTO `name_filter` VALUES (159, 'server');
INSERT INTO `name_filter` VALUES (160, 'sex');
INSERT INTO `name_filter` VALUES (161, 'shard');
INSERT INTO `name_filter` VALUES (162, 'shit');
INSERT INTO `name_filter` VALUES (163, 'shitstain');
INSERT INTO `name_filter` VALUES (269, 'sifilis');
INSERT INTO `name_filter` VALUES (270, 'siphilis');
INSERT INTO `name_filter` VALUES (164, 'sitt');
INSERT INTO `name_filter` VALUES (165, 'sittstain');
INSERT INTO `name_filter` VALUES (166, 'skank');
INSERT INTO `name_filter` VALUES (167, 'skanq');
INSERT INTO `name_filter` VALUES (168, 'sleeper');
INSERT INTO `name_filter` VALUES (169, 'slut');
INSERT INTO `name_filter` VALUES (170, 'snatch');
INSERT INTO `name_filter` VALUES (171, 'socialist');
INSERT INTO `name_filter` VALUES (172, 'sony');
INSERT INTO `name_filter` VALUES (173, 'spade');
INSERT INTO `name_filter` VALUES (174, 'spawnthemonkey');
INSERT INTO `name_filter` VALUES (175, 'speed');
INSERT INTO `name_filter` VALUES (176, 'spick');
INSERT INTO `name_filter` VALUES (177, 'splodge');
INSERT INTO `name_filter` VALUES (217, 'Sploog');
INSERT INTO `name_filter` VALUES (178, 'spoog');
INSERT INTO `name_filter` VALUES (179, 'spook');
INSERT INTO `name_filter` VALUES (180, 'stain');
INSERT INTO `name_filter` VALUES (181, 'sTFU');
INSERT INTO `name_filter` VALUES (182, 'suck');
INSERT INTO `name_filter` VALUES (183, 'suckme');
INSERT INTO `name_filter` VALUES (184, 'sucks');
INSERT INTO `name_filter` VALUES (185, 'sux');
INSERT INTO `name_filter` VALUES (268, 'syfhilis');
INSERT INTO `name_filter` VALUES (267, 'syfilis');
INSERT INTO `name_filter` VALUES (266, 'syphilis');
INSERT INTO `name_filter` VALUES (273, 'Tacvi');
INSERT INTO `name_filter` VALUES (186, 'tallon');
INSERT INTO `name_filter` VALUES (187, 'tarbaby');
INSERT INTO `name_filter` VALUES (188, 'tard');
INSERT INTO `name_filter` VALUES (254, 'teatea');
INSERT INTO `name_filter` VALUES (253, 'teetee');
INSERT INTO `name_filter` VALUES (250, 'terroris');
INSERT INTO `name_filter` VALUES (189, 'testicle');
INSERT INTO `name_filter` VALUES (190, 'tit');
INSERT INTO `name_filter` VALUES (191, 'tunare');
INSERT INTO `name_filter` VALUES (192, 'tvz');
INSERT INTO `name_filter` VALUES (193, 'twat');
INSERT INTO `name_filter` VALUES (194, 'tzvz');
INSERT INTO `name_filter` VALUES (252, 'vageen');
INSERT INTO `name_filter` VALUES (195, 'vagina');
INSERT INTO `name_filter` VALUES (232, 'vajay');
INSERT INTO `name_filter` VALUES (251, 'vajeen');
INSERT INTO `name_filter` VALUES (234, 'vajeh');
INSERT INTO `name_filter` VALUES (196, 'vallon');
INSERT INTO `name_filter` VALUES (197, 'vtz');
INSERT INTO `name_filter` VALUES (233, 'vuhjay');
INSERT INTO `name_filter` VALUES (235, 'vuhjey');
INSERT INTO `name_filter` VALUES (198, 'vztz');
INSERT INTO `name_filter` VALUES (199, 'wanker');
INSERT INTO `name_filter` VALUES (200, 'weed');
INSERT INTO `name_filter` VALUES (201, 'wetback');
INSERT INTO `name_filter` VALUES (202, 'whitehorse');
INSERT INTO `name_filter` VALUES (203, 'whore');
INSERT INTO `name_filter` VALUES (204, 'wildcard');
INSERT INTO `name_filter` VALUES (205, 'wtf');
INSERT INTO `name_filter` VALUES (246, 'xxx');
INSERT INTO `name_filter` VALUES (206, 'ylosh');
INSERT INTO `name_filter` VALUES (207, '_GM');

SET FOREIGN_KEY_CHECKS = 1;
