/*
 Navicat Premium Data Transfer

 Source Server         : MySQL
 Source Server Type    : MySQL
 Source Server Version : 50172
 Source Host           : localhost:3306
 Source Schema         : peqdb

 Target Server Type    : MySQL
 Target Server Version : 50172
 File Encoding         : 65001

 Date: 05/09/2020 15:10:01
*/

SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for rule_values
-- ----------------------------
DROP TABLE IF EXISTS `rule_values`;
CREATE TABLE `rule_values`  (
  `ruleset_id` tinyint(3) UNSIGNED NOT NULL DEFAULT 0,
  `rule_name` varchar(64) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '',
  `rule_value` varchar(30) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT '',
  `notes` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
  PRIMARY KEY (`ruleset_id`, `rule_name`) USING BTREE,
  INDEX `ruleset_id`(`ruleset_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of rule_values
-- ----------------------------
INSERT INTO `rule_values` VALUES (1, 'AA:ExpPerPoint', '23976503', 'Amount of exp per AA. Is the same as the amount of exp to go from level 51 to level 52');
INSERT INTO `rule_values` VALUES (1, 'AA:ModernAAScalingAALimit', '4000', 'The number of earned AA when AA XP scaling ends');
INSERT INTO `rule_values` VALUES (1, 'AA:ModernAAScalingAAMinimum', '0', 'The minimum number of earned AA before AA XP scaling begins');
INSERT INTO `rule_values` VALUES (1, 'AA:ModernAAScalingEnabled', 'false', 'Are we linearly scaling AA XP based on total # of earned AA?');
INSERT INTO `rule_values` VALUES (1, 'AA:ModernAAScalingStartPercent', '1000.0000000000000', '1000% or 10x AA XP at the start of the scaling range');
INSERT INTO `rule_values` VALUES (1, 'AA:NormalizedAAEnabled', 'false', 'TSS+ change to AA that normalizes AA XP to a fixed # of white con kills independent of level');
INSERT INTO `rule_values` VALUES (1, 'AA:NormalizedAANumberOfWhiteConPerAA', '25', 'The number of white con kills per AA point');
INSERT INTO `rule_values` VALUES (1, 'AA:Stacking', 'true', 'Allow AA that belong to the same group to stack on SOF+ clients');
INSERT INTO `rule_values` VALUES (1, 'Adventure:DistanceForRescueAccept', '10000.0000000000000', '');
INSERT INTO `rule_values` VALUES (1, 'Adventure:DistanceForRescueComplete', '2500.0000000000000', '');
INSERT INTO `rule_values` VALUES (1, 'Adventure:ItemIDToEnablePorts', '41000', '0 to disable, otherwise using a LDoN portal will require the user to have this item');
INSERT INTO `rule_values` VALUES (1, 'Adventure:LDoNAdventureExpireTime', '1800', '30 minutes to expire');
INSERT INTO `rule_values` VALUES (1, 'Adventure:LDoNBaseTrapDifficulty', '15.0000000000000', '');
INSERT INTO `rule_values` VALUES (1, 'Adventure:LDoNCriticalFailTrapThreshold', '10.0000000000000', '');
INSERT INTO `rule_values` VALUES (1, 'Adventure:LDoNTrapDistanceUse', '625', '');
INSERT INTO `rule_values` VALUES (1, 'Adventure:MaxLevelRange', '9', '');
INSERT INTO `rule_values` VALUES (1, 'Adventure:MaxNumberForGroup', '6', '');
INSERT INTO `rule_values` VALUES (1, 'Adventure:MaxNumberForRaid', '36', '');
INSERT INTO `rule_values` VALUES (1, 'Adventure:MinNumberForGroup', '2', '');
INSERT INTO `rule_values` VALUES (1, 'Adventure:MinNumberForRaid', '18', '');
INSERT INTO `rule_values` VALUES (1, 'Adventure:NumberKillsForBossSpawn', '40', '');
INSERT INTO `rule_values` VALUES (1, 'Aggro:AllowTickPulling', 'false', 'tick pulling is an exploit in an NPC\'s call for help fixed sometime in 2006 on live');
INSERT INTO `rule_values` VALUES (1, 'Aggro:ClientAggroCheckInterval', '6', 'Interval in which clients actually check for aggro - in seconds');
INSERT INTO `rule_values` VALUES (1, 'Aggro:CriticallyWoundedAggroMod', '100', '100%');
INSERT INTO `rule_values` VALUES (1, 'Aggro:CurrentTargetAggroMod', '0', '0% -- will prefer our current target to any other; makes it harder for our npcs to switch targets');
INSERT INTO `rule_values` VALUES (1, 'Aggro:IntAggroThreshold', '20', 'Int <= this will aggro regardless of level difference');
INSERT INTO `rule_values` VALUES (1, 'Aggro:MaxScalingProcAggro', '400', 'Set to -1 for no limit. Maxmimum amount of aggro that HP scaling SPA effect in a proc will add');
INSERT INTO `rule_values` VALUES (1, 'Aggro:MeleeRangeAggroMod', '20', '10%');
INSERT INTO `rule_values` VALUES (1, 'Aggro:MinAggroLevel', '18', 'For use with UseLevelAggro');
INSERT INTO `rule_values` VALUES (1, 'Aggro:NPCAggroMaxDistanceEnabled', 'true', 'If enabled, NPC\'s will drop aggro beyond 600 units or what is defined at the zone level');
INSERT INTO `rule_values` VALUES (1, 'Aggro:PetAttackRange', '40000.0000000000000', 'max squared range /pet attack works at default is 200');
INSERT INTO `rule_values` VALUES (1, 'Aggro:PetSpellAggroMod', '10', '');
INSERT INTO `rule_values` VALUES (1, 'Aggro:SittingAggroMod', '35', '35%');
INSERT INTO `rule_values` VALUES (1, 'Aggro:SmartAggroList', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Aggro:SongAggroMod', '33', '');
INSERT INTO `rule_values` VALUES (1, 'Aggro:SpellAggroMod', '100', '');
INSERT INTO `rule_values` VALUES (1, 'Aggro:TunnelVisionAggroMod', '0.7500000000000', 'people not currently the top hate generate this much hate on a Tunnel Vision mob');
INSERT INTO `rule_values` VALUES (1, 'Aggro:UseLevelAggro', 'true', 'MinAggroLevel rule value+ and Undead will aggro regardless of level difference. (this will disabled Rule:IntAggroThreshold if set to true)');
INSERT INTO `rule_values` VALUES (1, 'Bazaar:AuditTrail', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Bazaar:EnableWarpToTrader', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Bazaar:MaxBarterSearchResults', '200', 'The max results returned in the /barter search');
INSERT INTO `rule_values` VALUES (1, 'Bazaar:MaxSearchResults', '200', '');
INSERT INTO `rule_values` VALUES (1, 'Bugs:DumpTargetEntity', 'false', 'Dumps the target entity, if one is provided');
INSERT INTO `rule_values` VALUES (1, 'Bugs:ReportingSystemActive', 'true', 'Activates bug reporting');
INSERT INTO `rule_values` VALUES (1, 'Bugs:UseOldReportingMethod', 'true', 'Forces the use of the old bug reporting system');
INSERT INTO `rule_values` VALUES (1, 'Channels:DeleteTimer', '1440', 'Empty password protected channels will be deleted after this many minutes');
INSERT INTO `rule_values` VALUES (1, 'Channels:RequiredStatusAdmin', '251', 'Required status to administer chat channels');
INSERT INTO `rule_values` VALUES (1, 'Channels:RequiredStatusListAll', '251', 'Required status to list all chat channels');
INSERT INTO `rule_values` VALUES (1, 'Character:AAExpMultiplier', '0.6499999761581', '');
INSERT INTO `rule_values` VALUES (1, 'Character:ActiveInvSnapshots', 'false', 'Takes a periodic snapshot of inventory contents from online players');
INSERT INTO `rule_values` VALUES (1, 'Character:AllowCrossClassTrainers', 'false', '');
INSERT INTO `rule_values` VALUES (1, 'Character:AllowMQTarget', 'false', 'Disables putting players in the \'hackers\' list for targeting beyond the clip plane or attempting to target something untargetable');
INSERT INTO `rule_values` VALUES (1, 'Character:AutosaveIntervalS', '300', '0 = disabled');
INSERT INTO `rule_values` VALUES (1, 'Character:AvoidanceCap', '750', '750 Is a pretty good value, seen people dodge all attacks beyond 1,000 Avoidance');
INSERT INTO `rule_values` VALUES (1, 'Character:BaseHPRegenBonusRaces', '4352', 'a bitmask of race(s) that receive the regen bonus. Iksar (4096) & Troll (256) = 4352. see common/races.h for the bitmask values');
INSERT INTO `rule_values` VALUES (1, 'Character:BaseInstrumentSoftCap', '36', 'Softcap for instrument mods, 36 commonly referred to as \"3.6\" as well');
INSERT INTO `rule_values` VALUES (1, 'Character:BaseRunSpeedCap', '158', 'Base Run Speed Cap, on live it\'s 158% which will give you a runspeed of 1.580 hard capped to 225');
INSERT INTO `rule_values` VALUES (1, 'Character:BindAnywhere', 'false', '');
INSERT INTO `rule_values` VALUES (1, 'Character:BlueModifier', '100', '');
INSERT INTO `rule_values` VALUES (1, 'Character:CheckCursorEmptyWhenLooting', 'true', 'If true, a player cannot loot a corpse (player or NPC) with an item on their cursor');
INSERT INTO `rule_values` VALUES (1, 'Character:ConsumptionMultiplier', '100', 'item\'s hunger restored = this value * item\'s food level, 100 = normal, 50 = people eat 2x as fast, 200 = people eat 2x as slow');
INSERT INTO `rule_values` VALUES (1, 'Character:CorpseDecayTimeMS', '43200000', '');
INSERT INTO `rule_values` VALUES (1, 'Character:CorpseResTimeMS', '10800000', 'time before cant res corpse(3 hours)');
INSERT INTO `rule_values` VALUES (1, 'Character:DeathExpLossLevel', '10', 'Any level greater than this will lose exp on death');
INSERT INTO `rule_values` VALUES (1, 'Character:DeathExpLossMaxLevel', '255', 'Any level greater than this will no longer lose exp on death');
INSERT INTO `rule_values` VALUES (1, 'Character:DeathExpLossMultiplier', '3', 'Adjust how much exp is lost');
INSERT INTO `rule_values` VALUES (1, 'Character:DeathItemLossLevel', '10', '');
INSERT INTO `rule_values` VALUES (1, 'Character:DefaultGuild', '0', 'If not 0, new characters placed into the guild # indicated');
INSERT INTO `rule_values` VALUES (1, 'Character:DismountWater', 'true', 'Dismount horses when entering water');
INSERT INTO `rule_values` VALUES (1, 'Character:DragCorpseDistance', '400.0000000000000', 'If the corpse is <= this distance from the player, it won\'t move');
INSERT INTO `rule_values` VALUES (1, 'Character:EnableAggroMeter', 'true', 'Enable Aggro Meter, for users with RoF and later clients');
INSERT INTO `rule_values` VALUES (1, 'Character:EnableAvoidanceCap', 'false', '');
INSERT INTO `rule_values` VALUES (1, 'Character:EnableDiscoveredItems', 'false', 'If enabled, it enables EVENT_DISCOVER_ITEM and also saves character names and timestamps for the first time an item is discovered');
INSERT INTO `rule_values` VALUES (1, 'Character:EnableFoodRequirement', 'true', 'if disabled, food is no longer required');
INSERT INTO `rule_values` VALUES (1, 'Character:EnableHungerPenalties', 'false', 'being hungry/thirsty has negative effects -- it does appear normal live servers do not have penalties');
INSERT INTO `rule_values` VALUES (1, 'Character:EnableXTargetting', 'true', 'Enable Extended Targetting Window, for users with UF and later clients');
INSERT INTO `rule_values` VALUES (1, 'Character:EnduranceRegenMultiplier', '100', '');
INSERT INTO `rule_values` VALUES (1, 'Character:EnvironmentDamageMulipliter', '1.0000000000000', '');
INSERT INTO `rule_values` VALUES (1, 'Character:ExpMultiplier', '0.6499999761581', '');
INSERT INTO `rule_values` VALUES (1, 'Character:FeignKillsPet', 'false', '');
INSERT INTO `rule_values` VALUES (1, 'Character:FoodLossPerUpdate', '32', 'How much food/water you lose per stamina update');
INSERT INTO `rule_values` VALUES (1, 'Character:GrantHoTTOnCreate', 'false', 'Grant Health of Target\'s Target leadership AA on character creation');
INSERT INTO `rule_values` VALUES (1, 'Character:GreenModifier', '40', '');
INSERT INTO `rule_values` VALUES (1, 'Character:GroupExpMultiplier', '0.6499999761581', '');
INSERT INTO `rule_values` VALUES (1, 'Character:HasteCap', '100', 'Haste cap for non-v3(overhaste) haste');
INSERT INTO `rule_values` VALUES (1, 'Character:HealOnLevel', 'false', '');
INSERT INTO `rule_values` VALUES (1, 'Character:HPRegenMultiplier', '100', '');
INSERT INTO `rule_values` VALUES (1, 'Character:IksarCommonTongue', '95', '95 By default (live-like?)');
INSERT INTO `rule_values` VALUES (1, 'Character:InvSnapshotHistoryD', '30', 'Time (in days) to keep snapshot entries');
INSERT INTO `rule_values` VALUES (1, 'Character:InvSnapshotMinIntervalM', '180', 'Minimum time (in minutes) between inventory snapshots');
INSERT INTO `rule_values` VALUES (1, 'Character:InvSnapshotMinRetryM', '30', 'Time (in minutes) to re-attempt an inventory snapshot after a failure');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemAccuracyCap', '150', '');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemATKCap', '250', '');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemAvoidanceCap', '100', '');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemCastsUseFocus', 'false', 'If true, this allows item clickies to use focuses that have limited max levels on them');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemClairvoyanceCap', '250', '');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemCombatEffectsCap', '100', '');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemDamageShieldCap', '30', '');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemDoTShieldingCap', '35', '');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemDSMitigationCap', '50', '');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemEnduranceRegenCap', '15', '');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemExtraDmgCap', '150', 'Cap for bonuses to melee skills like Bash, Frenzy, etc');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemHealAmtCap', '250', '');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemHealthRegenCap', '30', '');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemManaRegenCap', '15', '');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemShieldingCap', '35', '');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemSpellDmgCap', '250', '');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemSpellShieldingCap', '35', '');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemStrikethroughCap', '35', '');
INSERT INTO `rule_values` VALUES (1, 'Character:ItemStunResistCap', '35', '');
INSERT INTO `rule_values` VALUES (1, 'Character:KeepLevelOverMax', 'false', 'Don\'t delevel a character that has somehow gone over the level cap');
INSERT INTO `rule_values` VALUES (1, 'Character:KillsPerGroupLeadershipAA', '250', 'Number of dark blues or above per Group Leadership AA');
INSERT INTO `rule_values` VALUES (1, 'Character:KillsPerRaidLeadershipAA', '250', 'Number of dark blues or above per Raid Leadership AA');
INSERT INTO `rule_values` VALUES (1, 'Character:LeaveCorpses', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Character:LeaveNakedCorpses', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Character:LightBlueModifier', '85', '');
INSERT INTO `rule_values` VALUES (1, 'Character:MaintainIntoxicationAcrossZones', 'true', 'If true, alcohol effects are maintained across zoning and logging out/in');
INSERT INTO `rule_values` VALUES (1, 'Character:ManaRegenMultiplier', '100', '');
INSERT INTO `rule_values` VALUES (1, 'Character:MarqueeHPUpdates', 'false', 'Will show Health % in center of screen < 100%');
INSERT INTO `rule_values` VALUES (1, 'Character:MaxCharmDurationForPlayerCharacter', '15', '');
INSERT INTO `rule_values` VALUES (1, 'Character:MaxDraggedCorpses', '2', '');
INSERT INTO `rule_values` VALUES (1, 'Character:MaxExpLevel', '70', 'Sets the Max Level attainable via Experience');
INSERT INTO `rule_values` VALUES (1, 'Character:MaxFearDurationForPlayerCharacter', '4', '4 tics, each tic calculates every 6 seconds');
INSERT INTO `rule_values` VALUES (1, 'Character:MaxLevel', '70', '');
INSERT INTO `rule_values` VALUES (1, 'Character:MinStatusForNoDropExemptions', '80', 'This allows status x and higher to trade no drop items');
INSERT INTO `rule_values` VALUES (1, 'Character:OgreCommonTongue', '95', '95 By default (live-like?)');
INSERT INTO `rule_values` VALUES (1, 'Character:OldMinMana', 'false', 'this is used for servers that want to follow older skill cap formulas so they can still have some regen w/o mediate');
INSERT INTO `rule_values` VALUES (1, 'Character:OPClientUpdateVisualDebug', 'false', 'Shows a pulse and forward directional particle each time the client sends its position to server');
INSERT INTO `rule_values` VALUES (1, 'Character:OrnamentationAugmentType', '20', 'Ornamentation Augment Type');
INSERT INTO `rule_values` VALUES (1, 'Character:PerCharacterBucketMaxLevel', 'false', 'This will check for data bucket \'CharMaxLevel\', if player tries to level beyond that point, it will not go beyond that level');
INSERT INTO `rule_values` VALUES (1, 'Character:PerCharacterQglobalMaxLevel', 'false', 'This will check for qglobal \'CharMaxLevel\' character qglobal (Type 5, \"\"), if player tries to level beyond that point, it will not go beyond that level');
INSERT INTO `rule_values` VALUES (1, 'Character:PetsUseReagents', 'true', 'Pets use reagent on spells');
INSERT INTO `rule_values` VALUES (1, 'Character:ProcessFearedProximity', 'false', 'Processes proximity checks when feared');
INSERT INTO `rule_values` VALUES (1, 'Character:RaidExpMultiplier', '0.2000000029802', '');
INSERT INTO `rule_values` VALUES (1, 'Character:RedModifier', '120', '');
INSERT INTO `rule_values` VALUES (1, 'Character:RespawnFromHover', 'false', 'Use Respawn window, or not');
INSERT INTO `rule_values` VALUES (1, 'Character:RespawnFromHoverTimer', '300', 'Respawn Window countdown timer, in SECONDS');
INSERT INTO `rule_values` VALUES (1, 'Character:RestRegenEnabled', 'true', 'Enable OOC Regen');
INSERT INTO `rule_values` VALUES (1, 'Character:RestRegenRaidTimeToActivate', '300', 'Time in seconds for rest state regen to kick in with a raid target');
INSERT INTO `rule_values` VALUES (1, 'Character:RestRegenTimeToActivate', '30', 'Time in seconds for rest state regen to kick in');
INSERT INTO `rule_values` VALUES (1, 'Character:RestrictSpellScribing', 'false', 'Restricts spell scribing to allowable races/classes of spell scroll, if true');
INSERT INTO `rule_values` VALUES (1, 'Character:SharedBankPlat', 'true', 'off by default to prevent duping for now');
INSERT INTO `rule_values` VALUES (1, 'Character:ShowExpValues', '0', '0 - normal, 1 - Show raw experience values, 2 - Show raw experience values AND percent');
INSERT INTO `rule_values` VALUES (1, 'Character:SkillCapMaxLevel', '-1', 'Sets the Max Level used for Skill Caps (from skill_caps table). -1 makes it use MaxLevel rule value. It is set to 75 because PEQ only has skillcaps up to that level, and grabbing the players\' skill past 75 will return 0, breaking all skills past that level. This helps servers with obsurd level caps (75+ level cap) function without any modifications');
INSERT INTO `rule_values` VALUES (1, 'Character:SkillUpModifier', '100', 'skill ups are at 100%');
INSERT INTO `rule_values` VALUES (1, 'Character:SoDClientUseSoDHPManaEnd', 'true', 'Setting this to true will allow SoD clients to use the SoD HP/Mana/End formulas and previous clients will use the old formulas');
INSERT INTO `rule_values` VALUES (1, 'Character:SoftDeletes', 'true', 'When characters are deleted in character select, they are only soft deleted');
INSERT INTO `rule_values` VALUES (1, 'Character:StatCap', '0', '');
INSERT INTO `rule_values` VALUES (1, 'Character:TradeskillUpAlchemy', '2', 'Alchemy skillup rate adjust. Lower is faster');
INSERT INTO `rule_values` VALUES (1, 'Character:TradeskillUpBaking', '2', 'Baking skillup rate adjust. Lower is faster');
INSERT INTO `rule_values` VALUES (1, 'Character:TradeskillUpBlacksmithing', '2', 'Blacksmithing skillup rate adjust. Lower is faster');
INSERT INTO `rule_values` VALUES (1, 'Character:TradeskillUpBrewing', '3', 'Brewing skillup rate adjust. Lower is faster');
INSERT INTO `rule_values` VALUES (1, 'Character:TradeskillUpFletching', '2', 'Fletching skillup rate adjust. Lower is faster');
INSERT INTO `rule_values` VALUES (1, 'Character:TradeskillUpJewelcrafting', '2', 'Jewelcrafting skillup rate adjust. Lower is faster');
INSERT INTO `rule_values` VALUES (1, 'Character:TradeskillUpMakePoison', '2', 'Make Poison skillup rate adjust. Lower is faster');
INSERT INTO `rule_values` VALUES (1, 'Character:TradeskillUpPottery', '4', 'Pottery skillup rate adjust. Lower is faster');
INSERT INTO `rule_values` VALUES (1, 'Character:TradeskillUpResearch', '1', 'Research skillup rate adjust. Lower is faster');
INSERT INTO `rule_values` VALUES (1, 'Character:TradeskillUpTinkering', '2', 'Tinkering skillup rate adjust. Lower is faster');
INSERT INTO `rule_values` VALUES (1, 'Character:TrollCommonTongue', '95', '95 By default (live-like?)');
INSERT INTO `rule_values` VALUES (1, 'Character:UnmemSpellsOnDeath', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Character:UseDeathExpLossMult', 'false', 'Adjust to use the above multiplier or to use code default');
INSERT INTO `rule_values` VALUES (1, 'Character:UseNewStatsWindow', 'true', 'New stats window shows everything');
INSERT INTO `rule_values` VALUES (1, 'Character:UseNoJunkFishing', 'false', 'Disregards junk items when fishing');
INSERT INTO `rule_values` VALUES (1, 'Character:UseOldBindWound', 'false', 'Uses the original bind wound behavior');
INSERT INTO `rule_values` VALUES (1, 'Character:UseOldClassExpPenalties', 'false', 'Setting this to true will enable old class exp penalties for Paladin, SK, Ranger, Bard, Monk, Wizard, Enchanter, Magician, and Necromancer, as well as the bonus for Rogues and Warriors');
INSERT INTO `rule_values` VALUES (1, 'Character:UseOldConSystem', 'false', 'Grant Health of Target\'s Target leadership AA on character creation');
INSERT INTO `rule_values` VALUES (1, 'Character:UseOldRaceExpPenalties', 'false', 'Setting this to true will enable racial exp penalties for Iksar, Troll, Ogre, and Barbarian, as well as the bonus for Halflings');
INSERT INTO `rule_values` VALUES (1, 'Character:UseOldRaceRezEffects', 'false', 'older clients had ID 757 for races with high starting STR, but it doesn\'t seem used anymore');
INSERT INTO `rule_values` VALUES (1, 'Character:UseRaceClassExpBonuses', 'true', 'Setting this to true will enable Class and Racial experience rate bonuses');
INSERT INTO `rule_values` VALUES (1, 'Character:UseSpellFileSongCap', 'true', 'When they removed the AA that increased the cap they removed the above and just use the spell field');
INSERT INTO `rule_values` VALUES (1, 'Character:UseStackablePickPocketing', 'true', 'Allows stackable pickpocketed items to stack instead of only being allowed in empty inventory slots');
INSERT INTO `rule_values` VALUES (1, 'Character:UseXPConScaling', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Character:WhiteModifier', '105', '');
INSERT INTO `rule_values` VALUES (1, 'Character:YellowModifier', '110', '');
INSERT INTO `rule_values` VALUES (1, 'Chat:EnableAntiSpam', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Chat:EnableMailKeyIPVerification', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Chat:EnableVoiceMacros', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Chat:GlobalChatLevelLimit', '1', 'level limit you need to of reached to talk in ooc/auction/chat if your karma is too low');
INSERT INTO `rule_values` VALUES (1, 'Chat:IntervalDurationMS', '60000', '');
INSERT INTO `rule_values` VALUES (1, 'Chat:KarmaGlobalChatLimit', '72', 'amount of karma you need to be able to talk in ooc/auction/chat below the level limit');
INSERT INTO `rule_values` VALUES (1, 'Chat:KarmaUpdateIntervalMS', '1200000', '');
INSERT INTO `rule_values` VALUES (1, 'Chat:MaximumMessagesPerInterval', '12', '');
INSERT INTO `rule_values` VALUES (1, 'Chat:MaxMessagesBeforeKick', '20', '');
INSERT INTO `rule_values` VALUES (1, 'Chat:MinimumMessagesPerInterval', '4', '');
INSERT INTO `rule_values` VALUES (1, 'Chat:MinStatusToBypassAntiSpam', '80', '');
INSERT INTO `rule_values` VALUES (1, 'Chat:ServerWideAuction', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Chat:ServerWideOOC', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Chat:SuppressCommandErrors', 'false', 'Do not suppress by default');
INSERT INTO `rule_values` VALUES (1, 'Client:UseLiveBlockedMessage', 'false', 'Allows players to see faction adjustments like Live');
INSERT INTO `rule_values` VALUES (1, 'Client:UseLiveFactionMessage', 'true', 'Allows players to see faction adjustments like Live');
INSERT INTO `rule_values` VALUES (1, 'Combat:AAMitigationACFactor', '3.0000000000000', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:ACthac0Factor', '0.5500000119209', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:ACthac20Factor', '0.5500000119209', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:AdjustProcPerMinute', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:AdjustSpecialProcPerMinute', 'false', 'Set PPM for special abilities like HeadShot (Live does this as of 4-14)');
INSERT INTO `rule_values` VALUES (1, 'Combat:AgiHitFactor', '0.0099999997765', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:ArcheryBaseDamageBonus', '1.0000000000000', '% Modifier to Base Archery Damage (.5 = 50% base damage, 1 = 100%, 2 = 200%)');
INSERT INTO `rule_values` VALUES (1, 'Combat:ArcheryBonusChance', '50', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:ArcheryBonusRequiresStationary', 'true', 'does the 2x archery bonus chance require a stationary npc');
INSERT INTO `rule_values` VALUES (1, 'Combat:ArcheryCritDifficulty', '3400', 'lower is easier');
INSERT INTO `rule_values` VALUES (1, 'Combat:ArcheryHitPenalty', '0.4499999880791', 'Archery has a hit penalty to try to help balance it with the plethora of long term +hit modifiers for it');
INSERT INTO `rule_values` VALUES (1, 'Combat:ArcheryNPCMultiplier', '1.0000000000000', 'this is multiplied by the regular dmg to get the archery dmg');
INSERT INTO `rule_values` VALUES (1, 'Combat:AssistNoTargetSelf', 'false', 'when assisting a target that does not have a target: true = target self, false = leave target as was before assist (false = live like)');
INSERT INTO `rule_values` VALUES (1, 'Combat:AvgDefProcsPerMinute', '2.0000000000000', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:AvgProcsPerMinute', '2.0000000000000', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:AvgSpecialProcsPerMinute', '2.0000000000000', 'Unclear what best value is atm');
INSERT INTO `rule_values` VALUES (1, 'Combat:BackstabBonus', '0', '% Modifier to damage');
INSERT INTO `rule_values` VALUES (1, 'Combat:BaseHitChance', '69.0000000000000', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:BaseProcChance', '0.0350000001490', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:BerserkerFrenzyEnd', '45', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:BerserkerFrenzyStart', '35', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:CasterACSoftcapReturn', '0.0599999986589', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:ChainACSoftcap', '200', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:ClassicMasterWu', 'false', 'classic master wu uses a random special, modern doesn\'t');
INSERT INTO `rule_values` VALUES (1, 'Combat:ClassicNPCBackstab', 'false', 'true disables npc facestab - npcs get normal attack if not behind');
INSERT INTO `rule_values` VALUES (1, 'Combat:ClientStunLevel', '55', 'This is the level where client kicks and bashes can stun the target');
INSERT INTO `rule_values` VALUES (1, 'Combat:ClothACSoftcap', '75', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:ClrRngMnkBrdACSoftcapReturn', '0.3030000030994', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:DefaultRampageTargets', '1', 'default number of people to hit with rampage');
INSERT INTO `rule_values` VALUES (1, 'Combat:DefProcPerMinAgiContrib', '0.0750000029802', 'How much agility contributes to defensive proc rate');
INSERT INTO `rule_values` VALUES (1, 'Combat:DragonPunchBonus', '20', '% Modifier that this skill gets to str and skill bonuses');
INSERT INTO `rule_values` VALUES (1, 'Combat:DruNecWizEncMagACSoftcapReturn', '0.2000000029802', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:EagleStrikeBonus', '15', '% Modifier that this skill gets to str and skill bonuses');
INSERT INTO `rule_values` VALUES (1, 'Combat:EnableFearPathing', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:EXPFromDmgShield', 'false', 'Determine if damage from a damage shield counts for EXP gain');
INSERT INTO `rule_values` VALUES (1, 'Combat:FleeGray', 'true', 'If true FleeGrayHPRatio will be used');
INSERT INTO `rule_values` VALUES (1, 'Combat:FleeGrayHPRatio', '50', 'HP % when a Gray NPC begins to flee');
INSERT INTO `rule_values` VALUES (1, 'Combat:FleeGrayMaxLevel', '18', 'NPC\'s above this level won\'t do gray/green con flee');
INSERT INTO `rule_values` VALUES (1, 'Combat:FleeHPRatio', '21', 'HP % when a NPC begins to flee');
INSERT INTO `rule_values` VALUES (1, 'Combat:FleeIfNotAlone', 'false', 'If false, mobs won\'t flee if other mobs are in combat with it');
INSERT INTO `rule_values` VALUES (1, 'Combat:FleeMultiplier', '2.0000000000000', 'Determines how quickly a NPC will slow down while fleeing. Decrease multiplier to slow NPC down quicker');
INSERT INTO `rule_values` VALUES (1, 'Combat:FlyingKickBonus', '25', '% Modifier that this skill gets to str and skill bonuses');
INSERT INTO `rule_values` VALUES (1, 'Combat:FrenzyBonus', '0', '% Modifier to damage');
INSERT INTO `rule_values` VALUES (1, 'Combat:HitBonusPerLevel', '1.2000000476837', 'You gain this % of hit for every level you are above your target');
INSERT INTO `rule_values` VALUES (1, 'Combat:HitCapPre10', '20', 'live has it capped at 20, see above');
INSERT INTO `rule_values` VALUES (1, 'Combat:HitCapPre20', '40', 'live has it capped at 40 for whatever dumb reason... this is mainly for custom servers');
INSERT INTO `rule_values` VALUES (1, 'Combat:HitFalloffMajor', '50.0000000000000', 'hit will fall off sharply if we\'re outside the minor and moderate range');
INSERT INTO `rule_values` VALUES (1, 'Combat:HitFalloffMinor', '5.0000000000000', 'hit will fall off up to 5% over the initial level range');
INSERT INTO `rule_values` VALUES (1, 'Combat:HitFalloffModerate', '7.0000000000000', 'hit will fall off up to 7% over the three levels after the initial level range');
INSERT INTO `rule_values` VALUES (1, 'Combat:KnightACSoftcapReturn', '0.3300000131130', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:LeatherACSoftcap', '100', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:LevelToStopACTwinkControl', '50', '1 will effectively disable it, 50 should give basically same results as current system');
INSERT INTO `rule_values` VALUES (1, 'Combat:LevelToStopDamageCaps', '0', '1 will effectively disable them, 20 should give basically same results as old incorrect system');
INSERT INTO `rule_values` VALUES (1, 'Combat:LowChainLeatherACSoftcapReturn', '0.1700000017881', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:LowPlateChainACSoftcapReturn', '0.2300000041723', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:MaxChancetoHit', '95.0000000000000', 'Maximum % chance to hit with regular melee/ranged');
INSERT INTO `rule_values` VALUES (1, 'Combat:MaxFlurryHits', '2', 'max number of extra hits from flurry');
INSERT INTO `rule_values` VALUES (1, 'Combat:MaxRampageTargets', '3', 'max number of people hit with rampage');
INSERT INTO `rule_values` VALUES (1, 'Combat:MeleeCritDifficulty', '8900', 'lower is easier');
INSERT INTO `rule_values` VALUES (1, 'Combat:MeleePush', 'true', 'enable melee push');
INSERT INTO `rule_values` VALUES (1, 'Combat:MeleePushChance', '50', '(NPCs) chance the target will be pushed. Made up, 100 actually isn\'t that bad');
INSERT INTO `rule_values` VALUES (1, 'Combat:MinChancetoHit', '5.0000000000000', 'Minimum % chance to hit with regular melee/ranged');
INSERT INTO `rule_values` VALUES (1, 'Combat:MinHastedDelay', '400', 'how fast we can get with haste');
INSERT INTO `rule_values` VALUES (1, 'Combat:MinRangedAttackDist', '25', 'Minimum Distance to use Ranged Attacks');
INSERT INTO `rule_values` VALUES (1, 'Combat:MiscACSoftcapReturn', '0.3000000119209', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:MonkACBonusWeight', '15', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:MonkACSoftcap', '120', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:MonkDamageTableBonus', '10', '% bonus monks get to their damage table calcs');
INSERT INTO `rule_values` VALUES (1, 'Combat:NPCACFactor', '2.2500000000000', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:NPCAssistCap', '15', 'Maxiumium number of NPCs that will assist another NPC at once');
INSERT INTO `rule_values` VALUES (1, 'Combat:NPCAssistCapTimer', '6000', 'Time in milliseconds a NPC will take to clear assist aggro cap space');
INSERT INTO `rule_values` VALUES (1, 'Combat:NPCBashKickLevel', '6', 'The level that npcs can KICK/BASH');
INSERT INTO `rule_values` VALUES (1, 'Combat:NPCBashKickStunChance', '15', 'Percent chance that a bash/kick will stun');
INSERT INTO `rule_values` VALUES (1, 'Combat:NPCBonusHitChance', '26.0000000000000', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:NPCCanCrit', 'false', 'true allows non PC pet NPCs to crit');
INSERT INTO `rule_values` VALUES (1, 'Combat:NPCFlurryChance', '20', 'Chance for NPC to flurry');
INSERT INTO `rule_values` VALUES (1, 'Combat:OldACSoftcapRules', 'false', 'use old softcaps');
INSERT INTO `rule_values` VALUES (1, 'Combat:OneProcPerWeapon', 'true', 'If enabled, One proc per weapon per round');
INSERT INTO `rule_values` VALUES (1, 'Combat:PalShdACSoftcapReturn', '0.3226000070572', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:PetAttackMagicLevel', '30', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:PetBaseCritChance', '0', 'Pet Base crit chance');
INSERT INTO `rule_values` VALUES (1, 'Combat:PlateACSoftcap', '300', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:ProcDexDivideBy', '11000.0000000000000', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:ProcPerMinDexContrib', '0.0750000029802', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:ProcTargetOnly', 'true', 'true = procs will only affect our target, false = procs will affect all of our targets');
INSERT INTO `rule_values` VALUES (1, 'Combat:ProjectileDmgOnImpact', 'true', 'If enabled, projectiles (ie arrows) will hit on impact, instead of instantly');
INSERT INTO `rule_values` VALUES (1, 'Combat:QuiverHasteCap', '1000', 'Quiver haste cap 1000 on live for a while, currently 700 on live');
INSERT INTO `rule_values` VALUES (1, 'Combat:RampageHitsTarget', 'false', 'rampage will hit the target if it still has targets left');
INSERT INTO `rule_values` VALUES (1, 'Combat:RogShmBstBerACSoftcapReturn', '0.2500000000000', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:RoundKickBonus', '5', '% Modifier that this skill gets to str and skill bonuses');
INSERT INTO `rule_values` VALUES (1, 'Combat:SoftcapFactor', '1.8799999952316', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:SpecialAttackACBonus', '15', 'Percent amount of damage per AC gained for certain special attacks (damage = AC*SpecialAttackACBonus/100)');
INSERT INTO `rule_values` VALUES (1, 'Combat:TauntOverLevel', 'true', 'Allows you to taunt NPC\'s over warriors level');
INSERT INTO `rule_values` VALUES (1, 'Combat:TauntSkillFalloff', '0.3300000131130', 'For every taunt skill point that\'s not maxed you lose this % chance to taunt');
INSERT INTO `rule_values` VALUES (1, 'Combat:ThrowingCritDifficulty', '1100', 'lower is easier');
INSERT INTO `rule_values` VALUES (1, 'Combat:TigerClawBonus', '10', '% Modifier that this skill gets to str and skill bonuses');
INSERT INTO `rule_values` VALUES (1, 'Combat:UseArcheryBonusRoll', 'false', 'Make the 51+ archery bonus require an actual roll');
INSERT INTO `rule_values` VALUES (1, 'Combat:UseExtendedPoisonProcs', 'false', 'Allow old school poisons to last until characrer zones, at a lower proc rate');
INSERT INTO `rule_values` VALUES (1, 'Combat:UseIntervalAC', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:UseLiveCombatRounds', 'true', 'turn this false if you don\'t want to worry about fixing up combat rounds for NPCs');
INSERT INTO `rule_values` VALUES (1, 'Combat:UseNPCDamageClassLevelMods', 'true', 'Uses GetClassLevelDamageMod calc in npc_scale_manager');
INSERT INTO `rule_values` VALUES (1, 'Combat:UseOldDamageIntervalRules', 'false', 'use old damage formulas for everything');
INSERT INTO `rule_values` VALUES (1, 'Combat:UseRevampHandToHand', 'false', 'use h2h revamped dmg/delays I believe this was implemented during SoF');
INSERT INTO `rule_values` VALUES (1, 'Combat:WarACSoftcapReturn', '0.3447999954224', 'new AC returns');
INSERT INTO `rule_values` VALUES (1, 'Combat:WarriorACSoftcapReturn', '0.4499999880791', '');
INSERT INTO `rule_values` VALUES (1, 'Combat:WeaponSkillFalloff', '0.3300000131130', 'For every weapon skill point that\'s not maxed you lose this % of hit');
INSERT INTO `rule_values` VALUES (1, 'Console:SessionTimeOut', '600000', 'Amount of time in ms for the console session to time out');
INSERT INTO `rule_values` VALUES (1, 'EventLog:RecordBuyFromMerchant', 'false', 'Record purchases by a player from an NPC merchant in eventlog table');
INSERT INTO `rule_values` VALUES (1, 'EventLog:RecordSellToMerchant', 'false', 'Record sales from a player to an NPC merchant in eventlog table');
INSERT INTO `rule_values` VALUES (1, 'Faction:AllyFactionMinimum', '1100', '');
INSERT INTO `rule_values` VALUES (1, 'Faction:AmiablyFactionMinimum', '100', '');
INSERT INTO `rule_values` VALUES (1, 'Faction:ApprehensivelyFactionMinimum', '-100', '');
INSERT INTO `rule_values` VALUES (1, 'Faction:DubiouslyFactionMinimum', '-500', '');
INSERT INTO `rule_values` VALUES (1, 'Faction:IndifferentlyFactionMinimum', '0', '');
INSERT INTO `rule_values` VALUES (1, 'Faction:KindlyFactionMinimum', '500', '');
INSERT INTO `rule_values` VALUES (1, 'Faction:ThreateninglyFactionMinimum', '-750', '');
INSERT INTO `rule_values` VALUES (1, 'Faction:WarmlyFactionMinimum', '750', '');
INSERT INTO `rule_values` VALUES (1, 'GM:MinStatusToLevelTarget', '100', '');
INSERT INTO `rule_values` VALUES (1, 'GM:MinStatusToSummonItem', '250', '');
INSERT INTO `rule_values` VALUES (1, 'GM:MinStatusToZoneAnywhere', '250', '');
INSERT INTO `rule_values` VALUES (1, 'Guild:MaxMembers', '2048', '');
INSERT INTO `rule_values` VALUES (1, 'Guild:PlayerCreationAllowed', 'true', 'Allow players to create a guild using the window in Underfoot+');
INSERT INTO `rule_values` VALUES (1, 'Guild:PlayerCreationLimit', '1', 'Only allow use of the UF+ window if the account has < than this number of guild leaders on it');
INSERT INTO `rule_values` VALUES (1, 'Guild:PlayerCreationRequiredLevel', '0', 'Required Level of the player attempting to create the guild');
INSERT INTO `rule_values` VALUES (1, 'Guild:PlayerCreationRequiredStatus', '0', 'Required admin status');
INSERT INTO `rule_values` VALUES (1, 'Guild:PlayerCreationRequiredTime', '0', 'Required Time Entitled On Account (in Minutes) to create the guild');
INSERT INTO `rule_values` VALUES (1, 'HotReload:QuestsRepopWhenPlayersNotInCombat', 'true', 'When a hot reload is triggered, the zone will repop when no clients are in combat');
INSERT INTO `rule_values` VALUES (1, 'HotReload:QuestsRepopWithReload', 'true', 'When a hot reload is triggered, the zone will repop');
INSERT INTO `rule_values` VALUES (1, 'HotReload:QuestsResetTimersWithReload', 'true', 'When a hot reload is triggered, quest timers will be reset');
INSERT INTO `rule_values` VALUES (1, 'Instances:GuildHallExpirationDays', '90', 'Amount of days before a Guild Hall instance expires');
INSERT INTO `rule_values` VALUES (1, 'Instances:RecycleInstanceIds', 'true', 'Will recycle free instance ids instead of gradually running out at 32k');
INSERT INTO `rule_values` VALUES (1, 'Instances:ReservedInstances', '30', 'Will reserve this many instance ids for globals... probably not a good idea to change this while a server is running');
INSERT INTO `rule_values` VALUES (1, 'Inventory:AllowAnyWeaponTransformation', 'false', 'Weapons can use any weapon transformation');
INSERT INTO `rule_values` VALUES (1, 'Inventory:DeleteTransformationMold', 'true', 'False if you want mold to last forever');
INSERT INTO `rule_values` VALUES (1, 'Inventory:EnforceAugmentRestriction', 'false', 'Forces augment slot restrictions');
INSERT INTO `rule_values` VALUES (1, 'Inventory:EnforceAugmentUsability', 'false', 'Forces augmented item usability');
INSERT INTO `rule_values` VALUES (1, 'Inventory:EnforceAugmentWear', 'false', 'Forces augment wear slot validation');
INSERT INTO `rule_values` VALUES (1, 'Inventory:TransformSummonedBags', 'false', 'Transforms summoned bags into disenchanted ones instead of deleting');
INSERT INTO `rule_values` VALUES (1, 'Logging:PrintFileFunctionAndLine', 'false', 'Ex: [World Server] [net.cpp::main:309] Loading variables...');
INSERT INTO `rule_values` VALUES (1, 'Mail:EnableMailSystem', 'true', 'If false, client won\'t bring up the Mail window');
INSERT INTO `rule_values` VALUES (1, 'Mail:ExpireRead', '31536000', '1 Year. Set to -1 for never');
INSERT INTO `rule_values` VALUES (1, 'Mail:ExpireTrash', '0', 'Time in seconds. 0 will delete all messages in the trash when the mailserver starts');
INSERT INTO `rule_values` VALUES (1, 'Mail:ExpireUnread', '31536000', '1 Year. Set to -1 for never');
INSERT INTO `rule_values` VALUES (1, 'Map:DistanceCanTravelBeforeAdjustment', '10.0000000000000', 'distance a mob can path before FixZ is called, depends on FixZWhenPathing');
INSERT INTO `rule_values` VALUES (1, 'Map:FindBestZHeightAdjust', '1', 'Adds this to the current Z before seeking the best Z position');
INSERT INTO `rule_values` VALUES (1, 'Map:FixPathingZMaxDeltaSendTo', '20.0000000000000', 'at runtime in SendTo: max change in Z to allow the BestZ code to apply');
INSERT INTO `rule_values` VALUES (1, 'Map:FixPathingZOnSendTo', 'false', 'try to repair Z coords in the SendTo routine as well');
INSERT INTO `rule_values` VALUES (1, 'Map:FixZWhenPathing', 'true', 'Automatically fix NPC Z coordinates when moving/pathing/engaged (Far less CPU intensive than its predecessor)');
INSERT INTO `rule_values` VALUES (1, 'Map:MobZVisualDebug', 'false', 'Displays spell effects determining whether or not NPC is hitting Best Z calcs (blue for hit, red for miss)');
INSERT INTO `rule_values` VALUES (1, 'Merchant:AllowCorpse', 'false', 'Can merchants generate a corpse');
INSERT INTO `rule_values` VALUES (1, 'Merchant:BuyCostMod', '0.9499999880791', 'Modifier for NPC buy price');
INSERT INTO `rule_values` VALUES (1, 'Merchant:ChaBonusMod', '3.4500000476837', 'Determines CHA cap, from 104 CHA. 3.45 is 132 CHA at apprehensive. 0.34 is 400 CHA at apprehensive');
INSERT INTO `rule_values` VALUES (1, 'Merchant:ChaPenaltyMod', '1.5199999809265', 'Determines CHA bottom, up to 102 CHA. 1.52 is 37 CHA at apprehensive. 0.98 is 0 CHA at apprehensive');
INSERT INTO `rule_values` VALUES (1, 'Merchant:EnableAltCurrencySell', 'true', 'Enables the ability to resell items to alternate currency merchants');
INSERT INTO `rule_values` VALUES (1, 'Merchant:PriceBonusPct', '4', 'Determines maximum price bonus from having good faction/CHA. Value is a percent');
INSERT INTO `rule_values` VALUES (1, 'Merchant:PricePenaltyPct', '4', 'Determines maximum price penalty from having bad faction/CHA. Value is a percent');
INSERT INTO `rule_values` VALUES (1, 'Merchant:SellCostMod', '1.0499999523163', 'Modifier for NPC sell price');
INSERT INTO `rule_values` VALUES (1, 'Merchant:UsePriceMod', 'true', 'Use faction/charisma price modifiers');
INSERT INTO `rule_values` VALUES (1, 'Mercs:AggroRadius', '100', 'Determines the distance from which a merc will aggro group member\'s target(also used to determine the distance at which a healer merc will begin healing a group member)');
INSERT INTO `rule_values` VALUES (1, 'Mercs:AggroRadiusPuller', '25', 'Determines the distance from which a merc will aggro group member\'s target, if they have the group role of puller (also used to determine the distance at which a healer merc will begin healing a group member, if they have the group role of puller)');
INSERT INTO `rule_values` VALUES (1, 'Mercs:AllowMercs', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Mercs:AllowMercSuspendInCombat', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Mercs:ChargeMercPurchaseCost', 'false', '');
INSERT INTO `rule_values` VALUES (1, 'Mercs:ChargeMercUpkeepCost', 'false', '');
INSERT INTO `rule_values` VALUES (1, 'Mercs:MercsUsePathing', 'true', 'Mercs will use node pathing when moving');
INSERT INTO `rule_values` VALUES (1, 'Mercs:ResurrectRadius', '50', 'Determines the distance from which a healer merc will attempt to resurrect a group member\'s corpse');
INSERT INTO `rule_values` VALUES (1, 'Mercs:ScaleRate', '100', '');
INSERT INTO `rule_values` VALUES (1, 'Mercs:SuspendIntervalMS', '10000', '');
INSERT INTO `rule_values` VALUES (1, 'Mercs:SuspendIntervalS', '10', '');
INSERT INTO `rule_values` VALUES (1, 'Mercs:UpkeepIntervalMS', '180000', '');
INSERT INTO `rule_values` VALUES (1, 'Mercs:UpkeepIntervalS', '180', '');
INSERT INTO `rule_values` VALUES (1, 'Network:ClientDataRate', '0.0000000000000', 'KB / sec, 0.0 disabled');
INSERT INTO `rule_values` VALUES (1, 'Network:CompressZoneStream', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Network:ResendDelayBaseMS', '100', '');
INSERT INTO `rule_values` VALUES (1, 'Network:ResendDelayFactor', '1.5000000000000', '');
INSERT INTO `rule_values` VALUES (1, 'Network:ResendDelayMaxMS', '5000', '');
INSERT INTO `rule_values` VALUES (1, 'Network:ResendDelayMinMS', '100', '');
INSERT INTO `rule_values` VALUES (1, 'NPC:BuffFriends', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'NPC:CorpseUnlockTimer', '150000', '');
INSERT INTO `rule_values` VALUES (1, 'NPC:EmptyNPCCorpseDecayTimeMS', '6000', '');
INSERT INTO `rule_values` VALUES (1, 'NPC:EnableMeritBasedFaction', 'false', 'If set to true, faction will given in the same way as experience (solo/group/raid)');
INSERT INTO `rule_values` VALUES (1, 'NPC:EnableNPCQuestJournal', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'NPC:LastFightingDelayMovingMax', '30000', '');
INSERT INTO `rule_values` VALUES (1, 'NPC:LastFightingDelayMovingMin', '5000', '');
INSERT INTO `rule_values` VALUES (1, 'NPC:LiveLikeEnrage', 'false', 'If set to true then only player controlled pets will enrage');
INSERT INTO `rule_values` VALUES (1, 'NPC:MajorNPCCorpseDecayTimeMS', '1800000', 'level >= 55');
INSERT INTO `rule_values` VALUES (1, 'NPC:MinorNPCCorpseDecayTimeMS', '600000', 'level < 55');
INSERT INTO `rule_values` VALUES (1, 'NPC:NewLevelScaling', 'true', 'Better level scaling, use old if new formulas would break your server');
INSERT INTO `rule_values` VALUES (1, 'NPC:NPCGateDistanceBind', '75', 'Distance from bind before NPC will attempt to gate');
INSERT INTO `rule_values` VALUES (1, 'NPC:NPCGateNearBind', 'false', 'Will NPC attempt to gate when near bind location?');
INSERT INTO `rule_values` VALUES (1, 'NPC:NPCGatePercent', '20', '% at which the NPC Will attempt to gate at');
INSERT INTO `rule_values` VALUES (1, 'NPC:NPCHealOnGate', 'true', 'Will the NPC Heal on Gate');
INSERT INTO `rule_values` VALUES (1, 'NPC:NPCHealOnGateAmount', '25.0000000000000', 'How much the npc will heal on gate if enabled');
INSERT INTO `rule_values` VALUES (1, 'NPC:NPCToNPCAggroTimerMax', '6000', '');
INSERT INTO `rule_values` VALUES (1, 'NPC:NPCToNPCAggroTimerMin', '500', '');
INSERT INTO `rule_values` VALUES (1, 'NPC:OOCRegen', '1', '');
INSERT INTO `rule_values` VALUES (1, 'NPC:ReturnNonQuestNoDropItems', 'true', 'Returns NO DROP items on NPCs that don\'t have an EVENT_TRADE sub in their script');
INSERT INTO `rule_values` VALUES (1, 'NPC:SayPauseTimeInSec', '10', '');
INSERT INTO `rule_values` VALUES (1, 'NPC:SmartLastFightingDelayMoving', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'NPC:StartEnrageValue', '9', '% HP that an NPC will begin to enrage');
INSERT INTO `rule_values` VALUES (1, 'NPC:UseBaneDamage', 'false', '');
INSERT INTO `rule_values` VALUES (1, 'NPC:UseClassAsLastName', 'true', 'Uses class archetype as LastName for npcs with none');
INSERT INTO `rule_values` VALUES (1, 'NPC:UseItemBonusesForNonPets', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'NPC:UseMeditateBasedManaRegen', 'false', 'Based NPC ooc regen on Meditate skill');
INSERT INTO `rule_values` VALUES (1, 'Pathing:Fear', 'true', 'Enable pathing for fear');
INSERT INTO `rule_values` VALUES (1, 'Pathing:Find', 'true', 'Enable pathing for FindPerson requests from the client');
INSERT INTO `rule_values` VALUES (1, 'Pathing:Guard', 'true', 'Enable pathing for mobs moving to their guard point');
INSERT INTO `rule_values` VALUES (1, 'Pathing:MaxNavmeshNodes', '1024', 'Max navmesh nodes in a traversable path');
INSERT INTO `rule_values` VALUES (1, 'Pathing:NavmeshStepSize', '100', '');
INSERT INTO `rule_values` VALUES (1, 'Pathing:ShortMovementUpdateRange', '130.0000000000000', '');
INSERT INTO `rule_values` VALUES (1, 'Pets:AttackCommandRange', '200.0000000000000', '');
INSERT INTO `rule_values` VALUES (1, 'Pets:CanTakeNoDrop', 'false', 'Can everyone trade nodrop gear to pets');
INSERT INTO `rule_values` VALUES (1, 'Pets:PetPowerLevelCap', '10.0000000000000', 'Max number of levels your pet can go up with pet power');
INSERT INTO `rule_values` VALUES (1, 'Pets:UnTargetableSwarmPet', 'false', '');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerDropItems', 'false', 'Logs Player dropping items');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogAAPurchases', 'false', 'Log Player AA Purchases');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogAARate', 'false', 'Logs Player AA Experience Rates');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogAlternateCurrencyTransactions', 'false', 'Log Player Alternate Currency Transactions');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogChat', 'false', 'Logs Player Chat');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogConnectDisconnect', 'false', 'Logs Player Connect Disconnect State');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogDeaths', 'false', 'Logs Player Deaths');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogDeletes', 'false', 'Logs Player Deletes');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogDropItem', 'false', 'Logs Player Drop Item');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogHandins', 'false', 'Logs Player Handins');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogIssuedCommandes', 'false', 'Log Player Issued Commands');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogKeyringAddition', 'false', 'Log PLayer Keyring additions');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogLevels', 'false', 'Logs Player Leveling/Deleveling');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogMerchantTransactions', 'false', 'Logs Merchant Transactions');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogMoneyTransactions', 'false', 'Log Player Money Transaction/Splits');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogMoves', 'false', 'Logs Player Moves');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogNPCKills', 'false', 'Logs Player NPC Kills');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogPCCoordinates', 'false', 'Logs Player Coordinates with certain events');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogQGlobalUpdate', 'false', 'Logs Player QGlobal Updates');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogTaskUpdates', 'false', 'Logs Player Task Updates');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogTrades', 'false', 'Logs Player Trades');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogTradeSkillEvents', 'false', 'Log Player Tradeskill Transactions');
INSERT INTO `rule_values` VALUES (1, 'QueryServ:PlayerLogZone', 'false', 'Logs Player Zone Events');
INSERT INTO `rule_values` VALUES (1, 'Range:Anims', '135', '');
INSERT INTO `rule_values` VALUES (1, 'Range:BeginCast', '200', '');
INSERT INTO `rule_values` VALUES (1, 'Range:ClientForceSpawnUpdateRange', '1000', '');
INSERT INTO `rule_values` VALUES (1, 'Range:ClientPositionUpdates', '300', '');
INSERT INTO `rule_values` VALUES (1, 'Range:CriticalDamage', '80', '');
INSERT INTO `rule_values` VALUES (1, 'Range:DamageMessages', '50', '');
INSERT INTO `rule_values` VALUES (1, 'Range:Emote', '135', '');
INSERT INTO `rule_values` VALUES (1, 'Range:MobCloseScanDistance', '600', '');
INSERT INTO `rule_values` VALUES (1, 'Range:MobPositionUpdates', '600', '');
INSERT INTO `rule_values` VALUES (1, 'Range:Say', '135', '');
INSERT INTO `rule_values` VALUES (1, 'Range:SongMessages', '75', '');
INSERT INTO `rule_values` VALUES (1, 'Range:SpellMessages', '75', '');
INSERT INTO `rule_values` VALUES (1, 'Range:SpellParticles', '135', '');
INSERT INTO `rule_values` VALUES (1, 'Skills:MaxTradeskillSearchSkillDiff', '50', '');
INSERT INTO `rule_values` VALUES (1, 'Skills:MaxTrainSpecializations', '50', 'Max level a GM trainer will train casting specializations');
INSERT INTO `rule_values` VALUES (1, 'Skills:MaxTrainTradeskills', '21', '');
INSERT INTO `rule_values` VALUES (1, 'Skills:RequireTomeHandin', 'false', 'Disable click-to-learn and force turnin to Guild Master');
INSERT INTO `rule_values` VALUES (1, 'Skills:SelfLanguageLearning', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Skills:SenseHeadingStartValue', '200', '');
INSERT INTO `rule_values` VALUES (1, 'Skills:SwimmingStartValue', '100', '');
INSERT INTO `rule_values` VALUES (1, 'Skills:TrainSenseHeading', 'false', '');
INSERT INTO `rule_values` VALUES (1, 'Skills:UseLimitTradeskillSearchSkillDiff', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Spells:AdditiveBonusWornType', '0', 'Calc worn bonuses to add together (instead of taking highest) if set to THIS worn type. (2=Will covert live items automatically)');
INSERT INTO `rule_values` VALUES (1, 'Spells:AI_EngagedBeneficialOtherChance', '25', 'Chance during second AI Cast check to do a beneficial spell on others');
INSERT INTO `rule_values` VALUES (1, 'Spells:AI_EngagedBeneficialSelfChance', '100', 'Chance during first AI Cast check to do a beneficial spell on self');
INSERT INTO `rule_values` VALUES (1, 'Spells:AI_EngagedDetrimentalChance', '20', 'Chance during third AI Cast check to do a determental spell on others');
INSERT INTO `rule_values` VALUES (1, 'Spells:AI_EngagedNoSpellMaxRecast', '1000', 'AI spell recast time(MS) check when no spell is cast engaged.(max time in random)');
INSERT INTO `rule_values` VALUES (1, 'Spells:AI_EngagedNoSpellMinRecast', '500', 'AI spell recast time(MS) check when no spell is cast while engaged. (min time in random)');
INSERT INTO `rule_values` VALUES (1, 'Spells:AI_HealHPPct', '50', 'HP Pct NPCs will start heals at (in and out of combat) if spell\'s max_hp is not set');
INSERT INTO `rule_values` VALUES (1, 'Spells:AI_IdleBeneficialChance', '100', 'Chance while idle to do a beneficial spell on self or others');
INSERT INTO `rule_values` VALUES (1, 'Spells:AI_IdleNoSpellMaxRecast', '60000', 'AI spell recast time(MS) check when no spell is cast while chasing target. (max time in random)');
INSERT INTO `rule_values` VALUES (1, 'Spells:AI_IdleNoSpellMinRecast', '6000', 'AI spell recast time(MS) check when no spell is cast while idle. (min time in random)');
INSERT INTO `rule_values` VALUES (1, 'Spells:AI_PursueDetrimentalChance', '90', 'Chance while chasing target to cast a detrimental spell');
INSERT INTO `rule_values` VALUES (1, 'Spells:AI_PursueNoSpellMaxRecast', '2000', 'AI spell recast time(MS) check when no spell is cast while chasing target. (max time in random)');
INSERT INTO `rule_values` VALUES (1, 'Spells:AI_PursueNoSpellMinRecast', '500', 'AI spell recast time(MS) check when no spell is cast while chasing target. (min time in random)');
INSERT INTO `rule_values` VALUES (1, 'Spells:AI_SpellCastFinishedFailRecast', '800', 'AI spell recast time(MS) when an spell is cast but fails (ie stunned)');
INSERT INTO `rule_values` VALUES (1, 'Spells:AllowItemTGB', 'false', 'TGB doesn\'t work with items on live, custom servers want it though');
INSERT INTO `rule_values` VALUES (1, 'Spells:AlwaysSendTargetsBuffs', 'false', 'ignore LAA level if true');
INSERT INTO `rule_values` VALUES (1, 'Spells:AutoResistDiff', '15', '');
INSERT INTO `rule_values` VALUES (1, 'Spells:AvgSpellProcsPerMinute', '6.0000000000000', 'Adjust rate for sympathetic spell procs');
INSERT INTO `rule_values` VALUES (1, 'Spells:BaseCritChance', '0', 'base % chance that everyone has to crit a spell');
INSERT INTO `rule_values` VALUES (1, 'Spells:BaseCritRatio', '100', 'base % bonus to damage on a successful spell crit. 100 = 2x damage');
INSERT INTO `rule_values` VALUES (1, 'Spells:BaseImmunityLevel', '55', 'The level that targets start to be immune to stun, fear and mez spells with a max level of 0');
INSERT INTO `rule_values` VALUES (1, 'Spells:BuffLevelRestrictions', 'true', 'Buffs will not land on low level toons like live');
INSERT INTO `rule_values` VALUES (1, 'Spells:CharismaCharmDuration', 'false', 'Allow CHA resist mod to extend charm duration');
INSERT INTO `rule_values` VALUES (1, 'Spells:CharismaEffectiveness', '10', 'Deterimes how much resist modification charisma applies to charm/pacify checks. Default 10 CHA = -1 resist mod');
INSERT INTO `rule_values` VALUES (1, 'Spells:CharismaEffectivenessCap', '255', 'Deterimes how much resist modification charisma applies to charm/pacify checks. Default 10 CHA = -1 resist mod');
INSERT INTO `rule_values` VALUES (1, 'Spells:CharmBreakCheckChance', '25', 'Determines chance for a charm break check to occur each buff tick');
INSERT INTO `rule_values` VALUES (1, 'Spells:CharmDisablesSpecialAbilities', 'false', 'When charm is cast on an NPC, strip their special abilities');
INSERT INTO `rule_values` VALUES (1, 'Spells:DeathSaveCharismaMod', '3', 'Determines how much charisma effects chance of death save firing');
INSERT INTO `rule_values` VALUES (1, 'Spells:DivineInterventionHeal', '8000', 'Divine intervention heal amount');
INSERT INTO `rule_values` VALUES (1, 'Spells:EnableBlockedBuffs', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Spells:EnableSpellBuckets', 'false', 'If Enabled, spells check the spell_buckets table and compare character data from their data buckets before allowing the spell to scribe with scribespells/traindiscs');
INSERT INTO `rule_values` VALUES (1, 'Spells:EnableSpellGlobals', 'false', 'If Enabled, spells check the spell_globals table and compare character data from their quest globals before allowing the spell to scribe with scribespells/traindiscs');
INSERT INTO `rule_values` VALUES (1, 'Spells:FearBreakCheckChance', '70', 'Determines chance for a fear break check to occur each buff tick');
INSERT INTO `rule_values` VALUES (1, 'Spells:FlatItemExtraSpellAmt', 'false', 'allow SpellDmg stat to affect all spells, regardless of cast time/cooldown/etc');
INSERT INTO `rule_values` VALUES (1, 'Spells:FocusCombatProcs', 'false', 'Allow all combat procs to receive focus effects');
INSERT INTO `rule_values` VALUES (1, 'Spells:FRProjectileItem_NPC', '80684', 'Item id for NPC Fire \'spell projectile\'');
INSERT INTO `rule_values` VALUES (1, 'Spells:FRProjectileItem_SOF', '80684', 'Item id for SOF clients for Fire \'spell projectile\'');
INSERT INTO `rule_values` VALUES (1, 'Spells:FRProjectileItem_Titanium', '1113', 'Item id for Titanium clients for Fire \'spell projectile\'');
INSERT INTO `rule_values` VALUES (1, 'Spells:IgnoreSpellDmgLvlRestriction', 'false', 'ignore the 5 level spread on applying SpellDmg');
INSERT INTO `rule_values` VALUES (1, 'Spells:Jun182014HundredHandsRevamp', 'true', 'this should be true for if you import a spell file newer than June 18, 2014');
INSERT INTO `rule_values` VALUES (1, 'Spells:LiveLikeFocusEffects', 'true', 'Determines whether specific healing, dmg and mana reduction focuses are randomized');
INSERT INTO `rule_values` VALUES (1, 'Spells:MaxBuffSlotsNPC', '85', 'default to Tit\'s limit');
INSERT INTO `rule_values` VALUES (1, 'Spells:MaxCastTimeReduction', '50', 'Max percent your spell cast time can be reduced by spell haste');
INSERT INTO `rule_values` VALUES (1, 'Spells:MaxDiscSlotsNPC', '1', 'NPCs don\'t have discs ...');
INSERT INTO `rule_values` VALUES (1, 'Spells:MaxSongSlotsNPC', '10', 'NPCs don\'t have songs ...');
INSERT INTO `rule_values` VALUES (1, 'Spells:MaxTotalSlotsNPC', '85', 'default to Tit\'s limit');
INSERT INTO `rule_values` VALUES (1, 'Spells:MaxTotalSlotsPET', '30', 'default to Tit\'s limit');
INSERT INTO `rule_values` VALUES (1, 'Spells:NPCIgnoreBaseImmunity', 'true', 'Whether or not NPCs get to ignore the BaseImmunityLevel for their spells');
INSERT INTO `rule_values` VALUES (1, 'Spells:NPCInnateProcOverride', 'true', 'NPC innate procs override the target type to single target');
INSERT INTO `rule_values` VALUES (1, 'Spells:NPCSpellPush', 'true', 'enable spell push on NPCs');
INSERT INTO `rule_values` VALUES (1, 'Spells:NPC_UseFocusFromItems', 'false', 'Allow npcs to use most item derived focus effects');
INSERT INTO `rule_values` VALUES (1, 'Spells:NPC_UseFocusFromSpells', 'true', 'Allow npcs to use most spell derived focus effects');
INSERT INTO `rule_values` VALUES (1, 'Spells:OldRainTargets', 'false', 'use old incorrectly implemented max targets for rains');
INSERT INTO `rule_values` VALUES (1, 'Spells:PartialHitChance', '0.6999999880791', 'The chance when a spell is resisted that it will partial hit');
INSERT INTO `rule_values` VALUES (1, 'Spells:PartialHitChanceFear', '0.2500000000000', 'The chance when a fear spell is resisted that it will partial hit');
INSERT INTO `rule_values` VALUES (1, 'Spells:PreNerfBardAEDoT', 'false', 'Allow bard AOE dots to damage targets when moving');
INSERT INTO `rule_values` VALUES (1, 'Spells:ReflectMessagesClose', 'true', 'Live functionality is for Reflect messages to show to players within close proximity, false shows just player reflecting');
INSERT INTO `rule_values` VALUES (1, 'Spells:ReflectType', '3', '0 = disabled, 1 = single target player spells only, 2 = all player spells, 3 = all single target spells, 4 = all spells');
INSERT INTO `rule_values` VALUES (1, 'Spells:ResistChance', '2.0000000000000', 'chance to resist given no resists and same level');
INSERT INTO `rule_values` VALUES (1, 'Spells:ResistFalloff', '67', 'Max that level that will adjust our resist chance based on level modifiers');
INSERT INTO `rule_values` VALUES (1, 'Spells:ResistMod', '0.4000000059605', 'multiplier, chance to resist = this * ResistAmount');
INSERT INTO `rule_values` VALUES (1, 'Spells:ResistPerLevelDiff', '85', '8.5 resist per level difference');
INSERT INTO `rule_values` VALUES (1, 'Spells:RootBreakCheckChance', '70', 'Determines chance for a root break check to occur each buff tick');
INSERT INTO `rule_values` VALUES (1, 'Spells:RootBreakFromSpells', '55', 'Chance for root to break when cast on');
INSERT INTO `rule_values` VALUES (1, 'Spells:SacrificeItemID', '9963', 'Item ID of the item Sacrifice will return (defaults to an EE)');
INSERT INTO `rule_values` VALUES (1, 'Spells:SacrificeMaxLevel', '70', 'last level Sacrifice will work on');
INSERT INTO `rule_values` VALUES (1, 'Spells:SacrificeMinLevel', '46', 'first level Sacrifice will work on');
INSERT INTO `rule_values` VALUES (1, 'Spells:SHDProcIDOffByOne', 'false', 'pre June 2009 SHD spell procs were off by 1, they stopped doing this in June 2009 (so UF+ spell files need this false)');
INSERT INTO `rule_values` VALUES (1, 'Spells:SuccorFailChance', '1', 'Determines chance for a succor spell not to teleport an invidual player');
INSERT INTO `rule_values` VALUES (1, 'Spells:SwarmPetTargetLock', 'false', 'Use old method of swarm pets target locking till target dies then despawning');
INSERT INTO `rule_values` VALUES (1, 'Spells:TranslocateTimeLimit', '0', 'If not zero, time in seconds to accept a Translocate');
INSERT INTO `rule_values` VALUES (1, 'Spells:UseAdditiveFocusFromWornSlot', 'false', 'Allows an additive focus effect to be calculated from worn slot');
INSERT INTO `rule_values` VALUES (1, 'Spells:UseCHAScribeHack', 'false', 'ScribeSpells and TrainDiscs quest functions will ignore entries where field 12 is CHA.  What\'s the best way to do this?');
INSERT INTO `rule_values` VALUES (1, 'Spells:UseLiveSpellProjectileGFX', 'false', 'Use spell projectile graphics set in the spells_new table (player_1). Server must be using UF+ spell file');
INSERT INTO `rule_values` VALUES (1, 'Spells:VirusSpreadDistance', '30', 'The distance a viral spell will jump to its next victim');
INSERT INTO `rule_values` VALUES (1, 'Spells:WizCritChance', '5', 'wiz\'s crit chance, on top of BaseCritChance');
INSERT INTO `rule_values` VALUES (1, 'Spells:WizCritLevel', '12', 'level wizards first get spell crits');
INSERT INTO `rule_values` VALUES (1, 'Spells:WizCritRatio', '0', 'wiz\'s crit bonus, on top of BaseCritRatio (should be 0 for Live-like)');
INSERT INTO `rule_values` VALUES (1, 'TaskSystem:EnableTaskProximity', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'TaskSystem:EnableTaskSystem', 'true', 'Globally enable or disable the Task system');
INSERT INTO `rule_values` VALUES (1, 'TaskSystem:KeepOneRecordPerCompletedTask', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'TaskSystem:PeriodicCheckTimer', '5', 'Seconds between checks for failed tasks. Also used by the \'Touch\' activity');
INSERT INTO `rule_values` VALUES (1, 'TaskSystem:RecordCompletedOptionalActivities', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'TaskSystem:RecordCompletedTasks', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Watermap:CheckForWaterAtWaypoints', 'true', 'Check if a mob has moved into/out of water when at waypoints and sets flymode');
INSERT INTO `rule_values` VALUES (1, 'Watermap:CheckForWaterOnSendTo', 'false', 'Checks if a mob has moved into/out of water on SendTo');
INSERT INTO `rule_values` VALUES (1, 'Watermap:CheckForWaterWhenFishing', 'true', 'Only lets a player fish near water (if a water map exists for the zone)');
INSERT INTO `rule_values` VALUES (1, 'Watermap:CheckForWaterWhenMoving', 'true', 'Checks if a mob has moved into/out of water each time it\'s loc is recalculated');
INSERT INTO `rule_values` VALUES (1, 'Watermap:CheckWaypointsInWaterWhenLoading', 'true', 'Does not apply BestZ as waypoints are loaded if they are in water');
INSERT INTO `rule_values` VALUES (1, 'Watermap:FishingLineLength', '100.0000000000000', 'If water is more than this far below the player, it is considered too far to fish');
INSERT INTO `rule_values` VALUES (1, 'Watermap:FishingLineStepSize', '1.0000000000000', 'Basic step size for fishing calc, too small and it will eat cpu, too large and it will miss potential water');
INSERT INTO `rule_values` VALUES (1, 'Watermap:FishingRodLength', '30.0000000000000', 'How far in front of player water must be for fishing to work');
INSERT INTO `rule_values` VALUES (1, 'World:AddMaxClientsPerIP', '-1', 'Maximum number of clients allowed to connect per IP address if account status is < ExemptMaxClientsStatus. Default value: -1 (feature disabled)');
INSERT INTO `rule_values` VALUES (1, 'World:AddMaxClientsStatus', '-1', 'Accounts with status >= this rule will be allowed to use the amount of accounts defined in the AddMaxClientsPerIP. Default value: -1 (feature disabled)');
INSERT INTO `rule_values` VALUES (1, 'World:ClearTempMerchantlist', 'false', 'Clears temp merchant items when world boots');
INSERT INTO `rule_values` VALUES (1, 'World:ClientKeepaliveTimeoutMS', '95000', '');
INSERT INTO `rule_values` VALUES (1, 'World:DeleteStaleCorpeBackups', 'true', 'Deletes stale corpse backups older than 2 weeks');
INSERT INTO `rule_values` VALUES (1, 'World:EnableIPExemptions', 'false', 'If True, ip_exemptions table is used, if there is no entry for the IP it will default to RuleI(World, MaxClientsPerIP)');
INSERT INTO `rule_values` VALUES (1, 'World:EnableReturnHomeButton', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'World:EnableTutorialButton', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'World:EnforceCharacterLimitAtLogin', 'false', '');
INSERT INTO `rule_values` VALUES (1, 'World:ExemptMaxClientsStatus', '-1', 'Exempt accounts from the MaxClientsPerIP and AddMaxClientsStatus rules, if their status is >= this value. Default value: -1 (feature disabled)');
INSERT INTO `rule_values` VALUES (1, 'World:ExpansionSettings', '16383', 'Sets the expansion settings for the server, This is sent on login to world and affects client expansion settings. Defaults to all expansions enabled up to TSS');
INSERT INTO `rule_values` VALUES (1, 'World:FVNoDropFlag', '0', 'Sets the Firiona Vie settings on the client. If set to 2, the flag will be set for GMs only, allowing trading of no-drop items');
INSERT INTO `rule_values` VALUES (1, 'World:GMAccountIPList', 'false', 'Check ip list against GM Accounts, AntiHack GM Accounts');
INSERT INTO `rule_values` VALUES (1, 'World:GuildBankZoneID', '345', '');
INSERT INTO `rule_values` VALUES (1, 'World:IPLimitDisconnectAll', 'false', '');
INSERT INTO `rule_values` VALUES (1, 'World:IsGMPetitionWindowEnabled', 'false', '');
INSERT INTO `rule_values` VALUES (1, 'World:MaxClientsPerIP', '-1', 'Maximum number of clients allowed to connect per IP address if account status is < AddMaxClientsStatus. Default value: -1 (feature disabled)');
INSERT INTO `rule_values` VALUES (1, 'World:MaxClientsSetByStatus', 'false', 'If True, IP Limiting will be set to the status on the account as long as the status is > MaxClientsPerIP');
INSERT INTO `rule_values` VALUES (1, 'World:MaxClientsSimplifiedLogic', 'false', 'New logic that only uses ExemptMaxClientsStatus and MaxClientsPerIP. Done on the loginserver. This mimics the P99-style special IP rules');
INSERT INTO `rule_values` VALUES (1, 'World:MaxLevelForTutorial', '15', '');
INSERT INTO `rule_values` VALUES (1, 'World:MinGMAntiHackStatus', '11', 'Minimum GM status to check against AntiHack list');
INSERT INTO `rule_values` VALUES (1, 'World:MinOfflineTimeToReturnHome', '21600', '21600 seconds is 6 Hours');
INSERT INTO `rule_values` VALUES (1, 'World:PVPMinLevel', '0', 'minimum level to pvp');
INSERT INTO `rule_values` VALUES (1, 'World:PVPSettings', '0', 'Sets the PVP settings for the server, 1 = Rallos Zek RuleSet, 2 = Tallon/Vallon Zek Ruleset, 4 = Sullon Zek Ruleset, 6 = Discord Ruleset, anything above 6 is the Discord Ruleset without the no-drop restrictions removed. TODO: Edit IsAttackAllowed in Zone to accomodate for these rules');
INSERT INTO `rule_values` VALUES (1, 'World:SoFStartZoneID', '-1', 'Sets the Starting Zone for SoF Clients separate from Titanium Clients (-1 is disabled)');
INSERT INTO `rule_values` VALUES (1, 'World:StartZoneSameAsBindOnCreation', 'true', 'Should the start zone ALWAYS be the same location as your bind?');
INSERT INTO `rule_values` VALUES (1, 'World:TellQueueSize', '20', '');
INSERT INTO `rule_values` VALUES (1, 'World:TitaniumStartZoneID', '-1', 'Sets the Starting Zone for Titanium Clients (-1 is disabled). Replaces the old method');
INSERT INTO `rule_values` VALUES (1, 'World:TutorialZoneID', '189', '');
INSERT INTO `rule_values` VALUES (1, 'World:UseBannedIPsTable', 'true', 'Toggle whether or not to check incoming client connections against the banned_ips table. Set this value to false to disable this feature');
INSERT INTO `rule_values` VALUES (1, 'World:UseClientBasedExpansionSettings', 'true', 'if true it will overrule World, ExpansionSettings and set someone\'s expansion based on the client they\'re using');
INSERT INTO `rule_values` VALUES (1, 'World:ZoneAutobootTimeoutMS', '120000', '');
INSERT INTO `rule_values` VALUES (1, 'Zone:AutoShutdownDelay', '5000', 'How long a dynamic zone stays loaded while empty');
INSERT INTO `rule_values` VALUES (1, 'Zone:ClientLinkdeadMS', '60000', 'the time a client remains link dead on the server after a sudden disconnection');
INSERT INTO `rule_values` VALUES (1, 'Zone:EbonCrystalItemID', '40902', '');
INSERT INTO `rule_values` VALUES (1, 'Zone:EnableLoggedOffReplenishments', 'true', '');
INSERT INTO `rule_values` VALUES (1, 'Zone:EnableMQGateDetector', 'true', 'Enable the MQGate Detector. Set to False to disable this feature');
INSERT INTO `rule_values` VALUES (1, 'Zone:EnableMQGhostDetector', 'true', 'Enable the MQGhost Detector. Set to False to disable this feature');
INSERT INTO `rule_values` VALUES (1, 'Zone:EnableMQWarpDetector', 'true', 'Enable the MQWarp Detector. Set to False to disable this feature');
INSERT INTO `rule_values` VALUES (1, 'Zone:EnableMQZoneDetector', 'true', 'Enable the MQZone Detector. Set to False to disable this feature');
INSERT INTO `rule_values` VALUES (1, 'Zone:EnableShadowrest', 'true', 'enables or disables the shadowrest zone feature for player corpses. Default is turned on');
INSERT INTO `rule_values` VALUES (1, 'Zone:EnableZoneControllerGlobals', 'false', 'Enables the ability to use quest globals with the zone controller NPC');
INSERT INTO `rule_values` VALUES (1, 'Zone:GlobalLootMultiplier', '1', 'Sets Global Loot drop multiplier for database based drops, useful for double, triple loot etc');
INSERT INTO `rule_values` VALUES (1, 'Zone:GraveyardTimeMS', '1200000', 'ms time until a player corpse is moved to a zone\'s graveyard, if one is specified for the zone');
INSERT INTO `rule_values` VALUES (1, 'Zone:HotZoneBonus', '0.7500000000000', '');
INSERT INTO `rule_values` VALUES (1, 'Zone:KillProcessOnDynamicShutdown', 'true', 'When process has booted a zone and has hit its zone shut down timer, it will hard kill the process to free memory back to the OS');
INSERT INTO `rule_values` VALUES (1, 'Zone:LevelBasedEXPMods', 'true', 'Allows you to use the level_exp_mods table in consideration to your players EXP hits');
INSERT INTO `rule_values` VALUES (1, 'Zone:MarkMQWarpLT', 'false', '');
INSERT INTO `rule_values` VALUES (1, 'Zone:MinOfflineTimeToReplenishments', '21600', '21600 seconds is 6 Hours');
INSERT INTO `rule_values` VALUES (1, 'Zone:MQGateExemptStatus', '80', 'Required status level to exempt the MQGateDetector. Set to -1 to disable this feature');
INSERT INTO `rule_values` VALUES (1, 'Zone:MQGhostExemptStatus', '80', 'Required status level to exempt the MGhostDetector. Set to -1 to disable this feature');
INSERT INTO `rule_values` VALUES (1, 'Zone:MQWarpDetectionDistanceFactor', '9.0000000000000', 'clients move at 4.4 about if in a straight line but with movement and to acct for lag we raise it a bit');
INSERT INTO `rule_values` VALUES (1, 'Zone:MQWarpExemptStatus', '80', 'Required status level to exempt the MQWarpDetector. Set to -1 to disable this feature');
INSERT INTO `rule_values` VALUES (1, 'Zone:MQZoneExemptStatus', '80', 'Required status level to exempt the MQZoneDetector. Set to -1 to disable this feature');
INSERT INTO `rule_values` VALUES (1, 'Zone:PEQZoneDebuff1', '4454', 'First debuff casted by #peqzone Default is Cursed Keeper\'s Blight');
INSERT INTO `rule_values` VALUES (1, 'Zone:PEQZoneDebuff2', '2209', 'Second debuff casted by #peqzone Default is Tendrils of Apathy');
INSERT INTO `rule_values` VALUES (1, 'Zone:PEQZoneReuseTime', '300', 'How long, in seconds, until you can reuse the #peqzone command');
INSERT INTO `rule_values` VALUES (1, 'Zone:RadiantCrystalItemID', '40903', '');
INSERT INTO `rule_values` VALUES (1, 'Zone:SecondsBeforeIdle', '60', 'Seconds before IDLE_WHEN_EMPTY define kicks in');
INSERT INTO `rule_values` VALUES (1, 'Zone:UsePEQZoneDebuffs', 'false', 'Will determine if #peqzone will debuff players or not when used');
INSERT INTO `rule_values` VALUES (1, 'Zone:UsePlayerCorpseBackups', 'true', 'Keeps backups of player corpses');
INSERT INTO `rule_values` VALUES (1, 'Zone:UseZoneController', 'false', 'Enables the ability to use persistent quest based zone controllers (zone_controller.pl/lua)');
INSERT INTO `rule_values` VALUES (1, 'Zone:WeatherTimer', '600', 'Weather timer when no duration is available');
INSERT INTO `rule_values` VALUES (2, 'NPC:EmptyNPCCorpseDecayTimeMS', '0', '');
INSERT INTO `rule_values` VALUES (2, 'NPC:LastFightingDelayMovingMax', '20000', '');
INSERT INTO `rule_values` VALUES (2, 'Spells:SuccorFailChance', '2', 'Determines chance for a succor spell not to teleport an invidual player');
INSERT INTO `rule_values` VALUES (4, 'NPC:EmptyNPCCorpseDecayTimeMS', '0', '');
INSERT INTO `rule_values` VALUES (4, 'NPC:LastFightingDelayMovingMax', '20000', '');
INSERT INTO `rule_values` VALUES (4, 'NPC:MinorNPCCorpseDecayTimeMS', '1800000', 'level < 55');
INSERT INTO `rule_values` VALUES (4, 'Spells:SuccorFailChance', '2', 'Determines chance for a succor spell not to teleport an invidual player');
INSERT INTO `rule_values` VALUES (5, 'Character:RestRegenTimeToActivate', '300', 'Time in seconds for rest state regen to kick in');
INSERT INTO `rule_values` VALUES (5, 'NPC:EmptyNPCCorpseDecayTimeMS', '0', '');
INSERT INTO `rule_values` VALUES (5, 'NPC:LastFightingDelayMovingMax', '20000', '');
INSERT INTO `rule_values` VALUES (5, 'NPC:MinorNPCCorpseDecayTimeMS', '1800000', 'level < 55');
INSERT INTO `rule_values` VALUES (5, 'Spells:SuccorFailChance', '2', 'Determines chance for a succor spell not to teleport an invidual player');
INSERT INTO `rule_values` VALUES (5, 'Zone:GraveyardTimeMS', '991200000', 'ms time until a player corpse is moved to a zone\'s graveyard, if one is specified for the zone');
INSERT INTO `rule_values` VALUES (6, 'Character:RestRegenTimeToActivate', '300', 'Time in seconds for rest state regen to kick in');
INSERT INTO `rule_values` VALUES (6, 'NPC:EmptyNPCCorpseDecayTimeMS', '0', '');
INSERT INTO `rule_values` VALUES (6, 'NPC:LastFightingDelayMovingMax', '20000', '');
INSERT INTO `rule_values` VALUES (6, 'NPC:MajorNPCCorpseDecayTimeMS', '0', 'level >= 55');
INSERT INTO `rule_values` VALUES (6, 'NPC:MinorNPCCorpseDecayTimeMS', '0', 'level < 55');
INSERT INTO `rule_values` VALUES (6, 'Spells:SuccorFailChance', '2', 'Determines chance for a succor spell not to teleport an invidual player');
INSERT INTO `rule_values` VALUES (6, 'Zone:GraveyardTimeMS', '991200000', 'ms time until a player corpse is moved to a zone\'s graveyard, if one is specified for the zone');
INSERT INTO `rule_values` VALUES (10, 'Adventure:LDoNAdventureExpireTime', '1800', '30 minutes to expire');
INSERT INTO `rule_values` VALUES (10, 'Adventure:LDoNBaseTrapDifficulty', '15.0', '');
INSERT INTO `rule_values` VALUES (10, 'Adventure:LDoNCriticalFailTrapThreshold', '10.0', '');
INSERT INTO `rule_values` VALUES (10, 'Adventure:LDoNTrapDistanceUse', '625', '');
INSERT INTO `rule_values` VALUES (10, 'Adventure:NumberKillsForBossSpawn', '45', '');
INSERT INTO `rule_values` VALUES (10, 'Aggro:IntAggroThreshold', '75', 'Int <= this will aggro regardless of level difference');
INSERT INTO `rule_values` VALUES (10, 'Aggro:MeleeRangeAggroMod', '10', '10%');
INSERT INTO `rule_values` VALUES (10, 'Aggro:TunnelVisionAggroMod', '0.75', 'people not currently the top hate generate this much hate on a Tunnel Vision mob');
INSERT INTO `rule_values` VALUES (10, 'Bazaar:MaxSearchResults', '50', '');
INSERT INTO `rule_values` VALUES (10, 'Character:AAExpMultiplier', '0.65', '');
INSERT INTO `rule_values` VALUES (10, 'Character:BaseHPRegenBonusRaces', '4352', 'a bitmask of race(s) that receive the regen bonus. Iksar (4096) & Troll (256) = 4352. see common/races.h for the bitmask values');
INSERT INTO `rule_values` VALUES (10, 'Character:BaseInstrumentSoftCap', '36', 'Softcap for instrument mods, 36 commonly referred to as \"3.6\" as well');
INSERT INTO `rule_values` VALUES (10, 'Character:BaseRunSpeedCap', '158', 'Base Run Speed Cap, on live it\'s 158% which will give you a runspeed of 1.580 hard capped to 225');
INSERT INTO `rule_values` VALUES (10, 'Character:CorpseDecayTimeMS', '10800000', '');
INSERT INTO `rule_values` VALUES (10, 'Character:ExpMultiplier', '0.65', '');
INSERT INTO `rule_values` VALUES (10, 'Character:FoodLossPerUpdate', '32', 'How much food/water you lose per stamina update');
INSERT INTO `rule_values` VALUES (10, 'Character:GroupExpMultiplier', '0.65', '');
INSERT INTO `rule_values` VALUES (10, 'Character:ItemATKCap', '250', '');
INSERT INTO `rule_values` VALUES (10, 'Character:ItemHealthRegenCap', '30', '');
INSERT INTO `rule_values` VALUES (10, 'Character:LightBlueModifier', '40', '');
INSERT INTO `rule_values` VALUES (10, 'Character:MaxExpLevel', '68', 'Sets the Max Level attainable via Experience');
INSERT INTO `rule_values` VALUES (10, 'Character:MaxLevel', '68', '');
INSERT INTO `rule_values` VALUES (10, 'Character:RedModifier', '150', '');
INSERT INTO `rule_values` VALUES (10, 'Character:SkillCapMaxLevel', '75', 'Sets the Max Level used for Skill Caps (from skill_caps table). -1 makes it use MaxLevel rule value. It is set to 75 because PEQ only has skillcaps up to that level, and grabbing the players\' skill past 75 will return 0, breaking all skills past that level. This helps servers with obsurd level caps (75+ level cap) function without any modifications');
INSERT INTO `rule_values` VALUES (10, 'Character:YellowModifier', '125', '');
INSERT INTO `rule_values` VALUES (10, 'Chat:GlobalChatLevelLimit', '1', 'level limit you need to of reached to talk in ooc/auction/chat if your karma is too low');
INSERT INTO `rule_values` VALUES (10, 'Chat:MinStatusToBypassAntiSpam', '100', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:AAMitigationACFactor', '3.0', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:ACthac0Factor', '0.55', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:ACthac20Factor', '0.55', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:ArcheryBonusChance', '50', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:ArcheryHitPenalty', '0.25', 'Archery has a hit penalty to try to help balance it with the plethora of long term +hit modifiers for it');
INSERT INTO `rule_values` VALUES (10, 'Combat:BerserkerFrenzyEnd', '45', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:BerserkerFrenzyStart', '35', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:CasterACSoftcapReturn', '0.06', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:ChainACSoftcap', '200', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:ClientStunLevel', '55', 'This is the level where client kicks and bashes can stun the target');
INSERT INTO `rule_values` VALUES (10, 'Combat:ClothACSoftcap', '75', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:ClrRngMnkBrdACSoftcapReturn', '0.3030', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:DefaultRampageTargets', '1', 'default number of people to hit with rampage');
INSERT INTO `rule_values` VALUES (10, 'Combat:DruNecWizEncMagACSoftcapReturn', '0.2000', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:FleeHPRatio', '25', 'HP % when a NPC begins to flee');
INSERT INTO `rule_values` VALUES (10, 'Combat:FleeMultiplier', '2.0', 'Determines how quickly a NPC will slow down while fleeing. Decrease multiplier to slow NPC down quicker');
INSERT INTO `rule_values` VALUES (10, 'Combat:HitCapPre10', '20', 'live has it capped at 20, see above');
INSERT INTO `rule_values` VALUES (10, 'Combat:HitCapPre20', '40', 'live has it capped at 40 for whatever dumb reason... this is mainly for custom servers');
INSERT INTO `rule_values` VALUES (10, 'Combat:KnightACSoftcapReturn', '0.33', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:LeatherACSoftcap', '100', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:LowChainLeatherACSoftcapReturn', '0.17', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:LowPlateChainACSoftcapReturn', '0.23', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:MinHastedDelay', '400', 'how fast we can get with haste');
INSERT INTO `rule_values` VALUES (10, 'Combat:MinRangedAttackDist', '25', 'Minimum Distance to use Ranged Attacks');
INSERT INTO `rule_values` VALUES (10, 'Combat:MiscACSoftcapReturn', '0.3', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:MonkACBonusWeight', '15', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:MonkACSoftcap', '120', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:MonkDamageTableBonus', '5', '% bonus monks get to their damage table calcs');
INSERT INTO `rule_values` VALUES (10, 'Combat:NPCACFactor', '2.25', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:PalShdACSoftcapReturn', '0.3226', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:PlateACSoftcap', '300', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:RogShmBstBerACSoftcapReturn', '0.2500', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:SoftcapFactor', '1.88', '');
INSERT INTO `rule_values` VALUES (10, 'Combat:TauntOverLevel', '1', 'Allows you to taunt NPC\'s over warriors level');
INSERT INTO `rule_values` VALUES (10, 'Combat:TauntSkillFalloff', '0.33', 'For every taunt skill point that\'s not maxed you lose this % chance to taunt');
INSERT INTO `rule_values` VALUES (10, 'Combat:WarACSoftcapReturn', '0.3448', 'new AC returns');
INSERT INTO `rule_values` VALUES (10, 'Combat:WarriorACSoftcapReturn', '0.45', '');
INSERT INTO `rule_values` VALUES (10, 'NPC:EmptyNPCCorpseDecayTimeMS', '0', '');
INSERT INTO `rule_values` VALUES (10, 'NPC:LastFightingDelayMovingMax', '20000', '');
INSERT INTO `rule_values` VALUES (10, 'NPC:LastFightingDelayMovingMin', '10000', '');
INSERT INTO `rule_values` VALUES (10, 'NPC:MajorNPCCorpseDecayTimeMS', '1500000', 'level >= 55');
INSERT INTO `rule_values` VALUES (10, 'NPC:MinorNPCCorpseDecayTimeMS', '450000', 'level < 55');
INSERT INTO `rule_values` VALUES (10, 'NPC:OOCRegen', '0', '');
INSERT INTO `rule_values` VALUES (10, 'NPC:SayPauseTimeInSec', '5', '');
INSERT INTO `rule_values` VALUES (10, 'Pets:AttackCommandRange', '150', '');
INSERT INTO `rule_values` VALUES (10, 'Spells:BaseImmunityLevel', '55', 'The level that targets start to be immune to stun, fear and mez spells with a max level of 0');
INSERT INTO `rule_values` VALUES (10, 'Spells:CharismaEffectivenessCap', '200', 'Deterimes how much resist modification charisma applies to charm/pacify checks. Default 10 CHA = -1 resist mod');
INSERT INTO `rule_values` VALUES (10, 'Spells:MaxTotalSlotsPET', '25', 'default to Tit\'s limit');
INSERT INTO `rule_values` VALUES (10, 'Spells:SacrificeMaxLevel', '69', 'last level Sacrifice will work on');
INSERT INTO `rule_values` VALUES (10, 'Spells:SuccorFailChance', '2', 'Determines chance for a succor spell not to teleport an invidual player');
INSERT INTO `rule_values` VALUES (10, 'Spells:WizCritChance', '7', 'wiz\'s crit chance, on top of BaseCritChance');
INSERT INTO `rule_values` VALUES (10, 'World:ClientKeepaliveTimeoutMS', '65000', '');
INSERT INTO `rule_values` VALUES (10, 'World:MaxLevelForTutorial', '10', '');
INSERT INTO `rule_values` VALUES (10, 'World:MinGMAntiHackStatus', '1', 'Minimum GM status to check against AntiHack list');
INSERT INTO `rule_values` VALUES (10, 'World:SoFStartZoneID', '-1', 'Sets the Starting Zone for SoF Clients separate from Titanium Clients (-1 is disabled)');
INSERT INTO `rule_values` VALUES (10, 'World:ZoneAutobootTimeoutMS', '60000', '');
INSERT INTO `rule_values` VALUES (10, 'Zone:EbonCrystalItemID', '40902', '');
INSERT INTO `rule_values` VALUES (10, 'Zone:LevelBasedEXPMods', 'false', 'Allows you to use the level_exp_mods table in consideration to your players EXP hits');
INSERT INTO `rule_values` VALUES (10, 'Zone:MQGateExemptStatus', '-1', 'Required status level to exempt the MQGateDetector. Set to -1 to disable this feature');
INSERT INTO `rule_values` VALUES (10, 'Zone:MQGhostExemptStatus', '-1', 'Required status level to exempt the MGhostDetector. Set to -1 to disable this feature');
INSERT INTO `rule_values` VALUES (10, 'Zone:MQWarpExemptStatus', '-1', 'Required status level to exempt the MQWarpDetector. Set to -1 to disable this feature');
INSERT INTO `rule_values` VALUES (10, 'Zone:MQZoneExemptStatus', '-1', 'Required status level to exempt the MQZoneDetector. Set to -1 to disable this feature');
INSERT INTO `rule_values` VALUES (10, 'Zone:PEQZoneReuseTime', '900', 'How long, in seconds, until you can reuse the #peqzone command');
INSERT INTO `rule_values` VALUES (10, 'Zone:RadiantCrystalItemID', '40903', '');

SET FOREIGN_KEY_CHECKS = 1;
